# Generated by Django 5.0.7 on 2025-10-08 18:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente de Aprobación"),
                            ("IN_PROGRESS", "Generación en Proceso"),
                            ("FULFILLED", "Satisfecha"),
                            ("REJECTED", "Rechazada"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Estado de la Solicitud",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Contenido",
                "verbose_name_plural": "Solicitudes de Contenido",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FreeContentRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Título del Curso"),
                ),
                (
                    "detailed_prompt",
                    models.TextField(verbose_name="Descripción Detallada / Prompt"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("approved", "Aprobada"),
                            ("rejected", "Rechazada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado de la Solicitud",
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("similar_exists", "Contenido Similar Existente"),
                            ("ethics_violation", "Incumplimiento del Código Ético"),
                            ("offensive_content", "Contenido de Carácter Ofensivo"),
                            ("other", "Otro (ver notas)"),
                        ],
                        help_text="Visible solo si el estado es 'Rechazada'.",
                        max_length=30,
                        null=True,
                        verbose_name="Motivo del Rechazo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Solicitud"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Contenido Libre",
                "verbose_name_plural": "A. Solicitudes de Contenido Libre",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedContentChunk",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="El número de orden para reconstruir el documento final.",
                        verbose_name="Orden de Sección",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="El texto generado por la IA para esta sección.",
                        verbose_name="Contenido de la Sección",
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este fragmento ya ha sido incluido en el ContenidoMaterial final.",
                        verbose_name="¿Procesado e incluido?",
                    ),
                ),
                (
                    "ai_sources",
                    models.TextField(
                        blank=True, null=True, verbose_name="Fuentes de la IA"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fragmento de Contenido Generado",
                "verbose_name_plural": "Fragmentos de Contenido Generado",
                "ordering": ["task", "order"],
            },
        ),
        migrations.CreateModel(
            name="PendingContentTask",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "course_title",
                    models.CharField(
                        blank=True,
                        help_text="Proporcionar solo si es un curso libre.",
                        max_length=255,
                        verbose_name="Título del Curso (Curso Libre)",
                    ),
                ),
                (
                    "prompt_text",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada o prompt para generar un curso libre.",
                        verbose_name="Descripción/Prompt (Curso Libre)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("PROCESSING", "Procesando"),
                            ("COMPLETED", "Completada"),
                            ("FAILED", "Fallida"),
                            ("FAILED_RETRYABLE", "Fallida (Reintentable)"),
                            ("FAILED_QUOTA", "Fallida (Límite de Cuota)"),
                            ("PAUSED", "Pausado por el Administrador"),
                        ],
                        default="PENDING",
                        max_length=30,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "structured_content",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Almacena artefactos intermedios como el temario o las secciones generadas.",
                        null=True,
                        verbose_name="Contenido Estructurado (JSON)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notas adicionales"),
                ),
                (
                    "log_file_path",
                    models.CharField(
                        blank=True,
                        help_text="Ruta al archivo de log detallado de la tarea.",
                        max_length=512,
                        null=True,
                        verbose_name="Ruta al Archivo de Log",
                    ),
                ),
                (
                    "task_log",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Registro de eventos y pasos de la tarea.",
                        verbose_name="Log de Tarea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea de Automatización de Contenido",
                "verbose_name_plural": "Tareas de Automatización de Contenido",
                "ordering": ["-created_at"],
            },
        ),
    ]
