# Generated by Django 5.0.7 on 2025-10-08 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic_structure", "0001_initial"),
        ("content_automation", "0001_initial"),
        ("contents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contentrequest",
            name="requesters",
            field=models.ManyToManyField(
                related_name="content_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuarios Solicitantes",
            ),
        ),
        migrations.AddField(
            model_name="contentrequest",
            name="subject",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_request",
                to="academic_structure.subject",
                verbose_name="Asignatura Solicitada",
            ),
        ),
        migrations.AddField(
            model_name="freecontentrequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="free_content_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario Solicitante",
            ),
        ),
        migrations.AddField(
            model_name="pendingcontenttask",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_content_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Asignado a",
            ),
        ),
        migrations.AddField(
            model_name="pendingcontenttask",
            name="content_material",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_task",
                to="contents.contentmaterial",
                verbose_name="Material de Contenido Resultante",
            ),
        ),
        migrations.AddField(
            model_name="pendingcontenttask",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                help_text="Asignar solo si es un curso derivado de una asignatura académica.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_tasks",
                to="academic_structure.subject",
                verbose_name="Asignatura (Curso Académico)",
            ),
        ),
        migrations.AddField(
            model_name="generatedcontentchunk",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_chunks",
                to="content_automation.pendingcontenttask",
                verbose_name="Tarea Asociada",
            ),
        ),
        migrations.AddConstraint(
            model_name="pendingcontenttask",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("status__in", ["COMPLETED", "FAILED"]), _negated=True),
                    ("subject__isnull", False),
                ),
                fields=("subject",),
                name="unique_active_academic_task_per_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="pendingcontenttask",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("subject__isnull", False),
                        ("course_title__exact", ""),
                        ("prompt_text__exact", ""),
                    ),
                    models.Q(
                        ("subject__isnull", True),
                        models.Q(("course_title__exact", ""), _negated=True),
                        models.Q(("prompt_text__exact", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="task_type_is_exclusive",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="generatedcontentchunk",
            unique_together={("task", "order")},
        ),
    ]
