# /home/MiguelAeTxio/CampuStudiOnline/content_automation/migrations/0003_apikey_automationsettings.py
# Generated by Django 5.0.7 on 2025-10-12 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_automation", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ej: 'Clave Primaria', 'Clave de Backup 1'",
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre Identificativo",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="La clave de API de Google Gemini.",
                        max_length=255,
                        unique=True,
                        verbose_name="Clave de API",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar para excluir esta clave de la rotación automática.",
                        verbose_name="¿Habilitada?",
                    ),
                ),
                (
                    "last_used",
                    models.DateTimeField(auto_now=True, verbose_name="Último Uso"),
                ),
            ],
            options={
                "verbose_name": "Clave de API de Gemini",
                "verbose_name_plural": "B. Claves de API de Gemini",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AutomationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_running",
                    models.BooleanField(
                        default=False,
                        help_text="Si está activado, la tarea 'always-on' buscará y procesará tareas pendientes.",
                        verbose_name="Interruptor Maestro de Automatización",
                    ),
                ),
                (
                    "active_api_key",
                    models.ForeignKey(
                        blank=True,
                        help_text="La clave que el sistema está utilizando actualmente para las generaciones.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="content_automation.apikey",
                        verbose_name="Clave de API Activa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del Centro de Control de Contenidos",
                "verbose_name_plural": "C. Configuración del Centro de Control de Contenidos",
            },
        ),
    ]
