# Generated by Django 5.0.7 on 2025-10-13 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0002_subject_content_hash"),
        ("content_automation", "0003_apikey_automationsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationsettings",
            name="seed_branch",
            field=models.ForeignKey(
                blank=True,
                help_text="La rama académica seleccionada como punto de partida para la generación.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academic_structure.branch",
                verbose_name="Rama Semilla",
            ),
        ),
        migrations.AddField(
            model_name="automationsettings",
            name="seed_degree",
            field=models.ForeignKey(
                blank=True,
                help_text="El grado académico seleccionado como punto de partida.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academic_structure.degree",
                verbose_name="Grado Semilla",
            ),
        ),
        migrations.AddField(
            model_name="automationsettings",
            name="seed_year",
            field=models.CharField(
                blank=True,
                help_text="El año académico específico (ej. 'Primero', 'Segundo') para acotar la generación.",
                max_length=20,
                verbose_name="Año Académico Semilla",
            ),
        ),
    ]
