# Generated by Django 5.0.7 on 2025-10-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_automation", "0004_automationsettings_seed_branch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente de Aprobación"),
                    ("APPROVED", "Aprobada para Automatización"),
                    ("IN_PROGRESS", "Generación en Proceso"),
                    ("FULFILLED", "Satisfecha"),
                    ("REJECTED", "Rechazada"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Estado de la Solicitud",
            ),
        ),
    ]
