# Generated by Django 5.0.7 on 2025-10-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_automation", "0005_alter_contentrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationsettings",
            name="last_run_status",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Estado del Último Ciclo"
            ),
        ),
        migrations.AddField(
            model_name="automationsettings",
            name="last_run_timestamp",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Última Ejecución"
            ),
        ),
    ]
