# Generated by Django 5.0.7 on 2025-10-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_automation", "0006_automationsettings_last_run_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationsettings",
            name="last_run_status",
            field=models.TextField(blank=True, verbose_name="Estado del Último Ciclo"),
        ),
    ]
