# Generated by Django 5.0.7 on 2025-10-16 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0002_subject_content_hash"),
        ("content_automation", "0007_alter_automationsettings_last_run_status"),
        ("contents", "0003_alter_favoritefolder_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pendingcontenttask",
            name="unique_active_academic_task_per_subject",
        ),
        migrations.AddField(
            model_name="automationsettings",
            name="event_log",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Historial de Eventos del Motor"
            ),
        ),
        migrations.AddField(
            model_name="pendingcontenttask",
            name="last_error",
            field=models.TextField(
                blank=True, null=True, verbose_name="Último Error Fatal"
            ),
        ),
        migrations.AlterField(
            model_name="pendingcontenttask",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("PROCESSING", "Procesando"),
                    ("COMPLETED", "Completada"),
                    ("FAILED", "Fallida (Manual)"),
                    ("FAILED_RETRYABLE", "Fallida (Reintentable)"),
                    ("FAILED_QUOTA", "Fallida (Límite de Cuota)"),
                    ("FAILED_FATAL", "Fallida (Fatal)"),
                    ("PAUSED", "Pausado por el Administrador"),
                ],
                default="PENDING",
                max_length=30,
                verbose_name="Estado",
            ),
        ),
        migrations.AddConstraint(
            model_name="pendingcontenttask",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(
                        ("status__in", ["COMPLETED", "FAILED", "FAILED_FATAL"]),
                        _negated=True,
                    ),
                    ("subject__isnull", False),
                ),
                fields=("subject",),
                name="unique_active_academic_task_per_subject",
            ),
        ),
    ]
