# Generated by Django 5.0.7 on 2025-10-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content_automation",
            "0008_remove_pendingcontenttask_unique_active_academic_task_per_subject_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingcontenttask",
            name="api_key_used",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Clave de API Utilizada",
            ),
        ),
        migrations.AddField(
            model_name="pendingcontenttask",
            name="section_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Número de Secciones"
            ),
        ),
        migrations.AddField(
            model_name="pendingcontenttask",
            name="task_origin",
            field=models.CharField(
                choices=[
                    ("MASS_GENERATION", "Masivo"),
                    ("APPROVED_REQUEST", "Solicitud Aprobada"),
                    ("MANUAL_CREATION", "Creación Manual"),
                    ("SYSTEM_RESTART", "Reinicio por Fallo"),
                ],
                default="MANUAL_CREATION",
                max_length=30,
                verbose_name="Origen de la Tarea",
            ),
        ),
    ]
