# Generated by Django 5.0.7 on 2025-10-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_automation", "0009_pendingcontenttask_api_key_used_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="is_high_priority_only",
            field=models.BooleanField(
                default=False,
                help_text="Si está marcada, esta clave solo se usará para tareas de alta prioridad (ej. autoevaluaciones).",
                verbose_name="Solo para Alta Prioridad",
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="is_quarantined",
            field=models.BooleanField(
                default=False,
                help_text="Marcado automáticamente si la clave alcanza el límite de cuota. Se liberará automáticamente.",
                verbose_name="En Cuarentena por Límite de Cuota",
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="quarantined_until",
            field=models.DateTimeField(
                blank=True,
                help_text="La clave no se usará hasta que pase esta fecha y hora.",
                null=True,
                verbose_name="Cuarentena hasta",
            ),
        ),
    ]
