# Generated by Django 5.0.7 on 2025-10-18 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "content_automation",
            "0010_apikey_is_high_priority_only_apikey_is_quarantined_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apikey",
            name="is_high_priority_only",
        ),
    ]
