# Generated by Django 5.0.7 on 2025-10-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_automation", "0011_remove_apikey_is_high_priority_only"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apikey",
            options={
                "ordering": ["id"],
                "verbose_name": "Clave de API de Gemini",
                "verbose_name_plural": "B. Claves de API de Gemini",
            },
        ),
        migrations.RemoveField(
            model_name="apikey",
            name="last_used",
        ),
        migrations.RemoveField(
            model_name="apikey",
            name="quarantined_until",
        ),
        migrations.AlterField(
            model_name="apikey",
            name="is_quarantined",
            field=models.BooleanField(
                default=False,
                help_text="Marcado si la clave falla persistentemente. Una tarea diaria la liberará.",
                verbose_name="En Cuarentena por Límite de Cuota",
            ),
        ),
    ]
