# Generated by Django 5.0.7 on 2025-10-26 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content_automation",
            "0012_alter_apikey_options_remove_apikey_last_used_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="automationsettings",
            name="quarantine_reset_time",
            field=models.TimeField(
                default=datetime.time(9, 5),
                help_text="La hora (en zona horaria del servidor) a la que se liberarán las claves en cuarentena.",
                verbose_name="Hora de Reseteo de Cuarentena",
            ),
        ),
    ]
