# Generated by Django 5.0.7 on 2025-10-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_automation", "0013_automationsettings_quarantine_reset_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationsettings",
            name="last_quarantine_reset_date",
            field=models.DateField(
                blank=True,
                help_text="Registra el último día que se ejecutó el reseteo para asegurar que solo ocurra una vez al día.",
                null=True,
                verbose_name="Fecha del Último Reseteo de Cuarentena",
            ),
        ),
    ]
