# Generated by Django 5.0.7 on 2025-10-26 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_automation", "0014_automationsettings_last_quarantine_reset_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationsettings",
            name="last_quarantine_reset_date",
            field=models.DateField(
                default=datetime.date(2000, 1, 1),
                help_text="Registra el último día que se ejecutó el reseteo para asegurar que solo ocurra una vez al día.",
                verbose_name="Fecha del Último Reseteo de Cuarentena",
            ),
        ),
    ]
