# Generated by Django 5.0.7 on 2025-11-03 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content_automation",
            "0015_alter_automationsettings_last_quarantine_reset_date",
        ),
        ("contents", "0005_contentmaterial_is_free_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingcontenttask",
            name="target_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Categoría seleccionada manualmente para contenido libre.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contents.maincategory",
            ),
        ),
        migrations.AddField(
            model_name="pendingcontenttask",
            name="target_discipline",
            field=models.ForeignKey(
                blank=True,
                help_text="Disciplina seleccionada manualmente para contenido libre.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contents.discipline",
            ),
        ),
    ]
