# Generated by Django 5.0.7 on 2025-11-05 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academic_structure",
            "0006_remove_subject_content_hash_contenthashfamily_and_more",
        ),
        ("content_automation", "0016_pendingcontenttask_target_category_and_more"),
        ("contents", "0006_update_public_status_by_rules"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pendingcontenttask",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(
                        ("status__in", ["COMPLETED", "FAILED", "FAILED_FATAL"]),
                        _negated=True,
                    ),
                    ("subject__isnull", True),
                ),
                fields=("course_title",),
                name="unique_active_free_task_per_title",
            ),
        ),
    ]
