# Generated by Django 5.0.7 on 2025-11-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "content_automation",
            "0017_pendingcontenttask_unique_active_free_task_per_title",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendingcontenttask",
            name="target_category",
        ),
        migrations.RemoveField(
            model_name="pendingcontenttask",
            name="target_discipline",
        ),
    ]
