# Generated by Django 5.0.7 on 2025-11-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content_automation", "0018_remove_pendingcontenttask_target_category_and_more"),
        # Añadimos dependencia explícita a la nueva migración de orchestrator
        ("orchestrator", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="ApiKey",
                ),
                migrations.DeleteModel(
                    name="AutomationSettings",
                ),
            ],
            database_operations=[],  # No hacer nada en la BBDD
        ),
    ]
