# Generated by Django 5.0.7 on 2025-10-08 18:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic_structure", "0001_initial"),
        ("auth", "0001_initial"),
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "affiliated_university",
                    models.ForeignKey(
                        blank=True,
                        help_text="Afiliación universitaria verificada por un administrador. No editable por el usuario en su perfil.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="university_members",
                        to="academic_structure.university",
                        verbose_name="Universidad afiliada (verificada)",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="customuser_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="Grupos",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="customuser_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="Permisos de usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Carrera"
                    ),
                ),
                (
                    "current_year",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Curso Actual"
                    ),
                ),
                (
                    "university",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Universidad"
                    ),
                ),
                (
                    "hobbies",
                    models.TextField(blank=True, verbose_name="Gustos e Intereses"),
                ),
                (
                    "work_experience",
                    models.TextField(blank=True, verbose_name="Experiencia Laboral"),
                ),
                (
                    "public_personal_description",
                    models.TextField(
                        blank=True,
                        help_text="Una breve introducción sobre ti para mostrar en tu portafolio.",
                        verbose_name="Descripción personal para el portafolio",
                    ),
                ),
                (
                    "professional_title",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Desarrollador Web Fullstack, Estudiante de Marketing Digital.",
                        max_length=255,
                        verbose_name="Título profesional o Headline",
                    ),
                ),
                (
                    "show_phone_in_portfolio",
                    models.BooleanField(
                        default=False,
                        verbose_name="Mostrar teléfono en el portafolio público",
                    ),
                ),
                (
                    "show_degree_in_portfolio",
                    models.BooleanField(
                        default=False,
                        verbose_name="Mostrar carrera en el portafolio público",
                    ),
                ),
                (
                    "show_current_year_in_portfolio",
                    models.BooleanField(
                        default=False,
                        verbose_name="Mostrar curso actual en el portafolio público",
                    ),
                ),
                (
                    "show_university_in_portfolio",
                    models.BooleanField(
                        default=False,
                        verbose_name="Mostrar universidad en el portafolio público",
                    ),
                ),
                (
                    "show_hobbies_in_portfolio",
                    models.BooleanField(
                        default=False,
                        verbose_name="Mostrar gustos e intereses en el portafolio público",
                    ),
                ),
                (
                    "show_work_experience_in_portfolio",
                    models.BooleanField(
                        default=False,
                        verbose_name="Mostrar experiencia laboral en el portafolio público",
                    ),
                ),
                (
                    "show_chat_rooms_in_portfolio",
                    models.BooleanField(
                        default=False,
                        verbose_name="Mostrar mi directorio de salas de chat en el portafolio público",
                    ),
                ),
                (
                    "show_personal_description_in_portfolio",
                    models.BooleanField(
                        default=True,
                        verbose_name="Mostrar descripción personal en el portafolio",
                    ),
                ),
                (
                    "show_professional_title_in_portfolio",
                    models.BooleanField(
                        default=True,
                        verbose_name="Mostrar título profesional en el portafolio",
                    ),
                ),
                (
                    "show_short_messages_in_portfolio",
                    models.BooleanField(
                        default=True,
                        verbose_name="Mostrar mensajes cortos en el portafolio público",
                    ),
                ),
                (
                    "show_user_links_in_portfolio",
                    models.BooleanField(
                        default=True,
                        verbose_name="Mostrar mis enlaces de interés en el portafolio público",
                    ),
                ),
                (
                    "public_key",
                    models.TextField(
                        blank=True,
                        help_text="Clave pública del usuario, en formato JWK, para el cifrado de mensajes.",
                        null=True,
                        verbose_name="Clave Pública para Cifrado",
                    ),
                ),
                (
                    "encrypted_private_key",
                    models.TextField(
                        blank=True,
                        help_text="Clave privada del usuario, cifrada con su contraseña, para recuperación entre dispositivos.",
                        null=True,
                        verbose_name="Clave Privada Cifrada",
                    ),
                ),
                (
                    "encryption_salt",
                    models.CharField(
                        blank=True,
                        help_text="Sal criptográfica única para este usuario, usada para derivar la clave de cifrado. No cambiar manualmente.",
                        max_length=100,
                        null=True,
                        verbose_name="Sal para Cifrado",
                    ),
                ),
                (
                    "last_checked_chat_activity",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Registra la última vez que el usuario revisó la actividad de sus salas de chat en su portafolio.",
                        verbose_name="Última revisión de actividad en chat",
                    ),
                ),
                (
                    "ia_requests_today",
                    models.IntegerField(
                        default=0,
                        help_text="Contador de peticiones a la API de IA realizadas hoy por el usuario.",
                        verbose_name="Peticiones de IA hoy",
                    ),
                ),
                (
                    "last_ia_request_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de la última petición para reiniciar el contador diario.",
                        null=True,
                        verbose_name="Fecha de última petición de IA",
                    ),
                ),
                (
                    "profile_created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación del perfil"
                    ),
                ),
                (
                    "profile_updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización del perfil"
                    ),
                ),
                (
                    "blocked_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Otros usuarios que este perfil ha decidido bloquear.",
                        related_name="blocked_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuarios Bloqueados",
                    ),
                ),
                (
                    "favorite_content",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Contenido que el usuario ha marcado como favorito.",
                        related_name="favorited_by",
                        to="contents.contentmaterial",
                        verbose_name="Contenido Favorito",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuario",
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="ArchivedKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "encrypted_private_key",
                    models.TextField(
                        help_text="Una clave privada anterior, cifrada con la contraseña del usuario en ese momento.",
                        verbose_name="Clave Privada Cifrada Archivada",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Archivado",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archived_keys",
                        to="users.userprofile",
                        verbose_name="Perfil de Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clave Archivada",
                "verbose_name_plural": "Claves Archivadas",
                "ordering": ["-archived_at"],
            },
        ),
    ]
