# Generated by Django 5.0.7 on 2025-11-27 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academic_structure",
            "0007_alter_university_options_alter_branch_university_and_more",
        ),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="affiliated_university",
            field=models.ForeignKey(
                blank=True,
                help_text="Afiliación institucional verificada por un administrador. No editable por el usuario en su perfil.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="university_members",
                to="academic_structure.university",
                verbose_name="Institución afiliada (verificada)",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="show_university_in_portfolio",
            field=models.BooleanField(
                default=False,
                verbose_name="Mostrar institución en el portafolio público",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="university",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Institución"
            ),
        ),
    ]
