# Generated by Django 5.0.7 on 2025-12-20 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_affiliated_university_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="has_claimed_assessment_incentive",
            field=models.BooleanField(
                default=False,
                help_text="True si ya se ha contabilizado la conversión por primera evaluación.",
                verbose_name="Incentivo de Evaluación Reclamado",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="has_claimed_copy_incentive",
            field=models.BooleanField(
                default=False,
                help_text="True si ya se ha contabilizado la conversión por primera copia.",
                verbose_name="Incentivo de Copia Reclamado",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                help_text="El comercial dueño del código con el que este usuario se registró.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Referido por (Comercial)",
            ),
        ),
        migrations.CreateModel(
            name="RecommendationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código alfanumérico de 4 caracteres (Ej: 4A7K).",
                        max_length=4,
                        unique=True,
                        verbose_name="Código de Conversión",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este código ya ha sido canjeado por un usuario.",
                        verbose_name="¿Usado?",
                    ),
                ),
                (
                    "date_redeemed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Canje"
                    ),
                ),
                (
                    "redeemed_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redeemed_code",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Canjeado por (Usuario)",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "Comerciales"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Comercial (Vendor)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Código de Recomendación",
                "verbose_name_plural": "Códigos de Recomendación",
            },
        ),
    ]
