# Generated by Django 5.0.7 on 2025-12-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userprofile_has_claimed_assessment_incentive_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recommendationcode",
            name="is_used",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pending_referral_code",
            field=models.CharField(
                blank=True,
                help_text="Código temporal almacenado durante el registro y antes de la activación.",
                max_length=4,
                null=True,
                verbose_name="Código de referido pendiente",
            ),
        ),
    ]
