# Generated by Django 5.0.7 on 2026-01-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_recommendationcode_is_used_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="accepts_marketing",
            field=models.BooleanField(
                default=True,
                help_text="Indica si el usuario desea recibir correos administrativos no críticos.",
                verbose_name="Acepta comunicaciones comerciales",
            ),
        ),
    ]
