# Generated by Django 5.0.7 on 2026-01-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_userprofile_accepts_marketing"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaConversionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=100)),
                (
                    "user_details",
                    models.JSONField(
                        help_text="Contiene email_hash, client_ip_address, client_user_agent, fbc, fbp"
                    ),
                ),
                ("event_id", models.CharField(blank=True, max_length=255, null=True)),
                ("source_url", models.URLField(blank=True, max_length=500, null=True)),
                ("custom_data_params", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "verbose_name": "Evento de Conversión Meta",
                "verbose_name_plural": "Eventos de Conversión Meta",
                "ordering": ["created_at"],
            },
        ),
    ]
