# Generated by Django 5.0.7 on 2025-11-15 15:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "academic_structure",
            "0006_remove_subject_content_hash_contenthashfamily_and_more",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="ApiKey",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("name", models.CharField(help_text="Ej: 'Clave Primaria', 'Clave de Backup 1'", max_length=100, unique=True, verbose_name="Nombre Identificativo")),
                        ("key", models.CharField(help_text="La clave de API de Google Gemini.", max_length=255, unique=True, verbose_name="Clave de API")),
                        ("is_enabled", models.BooleanField(default=True, help_text="Desmarcar para excluir esta clave de la rotación automática.", verbose_name="¿Habilitada?")),
                        ("is_quarantined", models.BooleanField(default=False, help_text="Marcado si la clave falla persistentemente. Una tarea diaria la liberará.", verbose_name="En Cuarentena por Límite de Cuota")),
                    ],
                    options={
                        "verbose_name": "Clave de API de Gemini",
                        "verbose_name_plural": "B. Claves de API de Gemini",
                        "ordering": ["id"],
                        "db_table": "content_automation_apikey",
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="AutomationSettings",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("is_running", models.BooleanField(default=False, help_text="Si está activado, la tarea 'always-on' buscará y procesará tareas pendientes.", verbose_name="Interruptor Maestro de Automatización")),
                        ("quarantine_reset_time", models.TimeField(default=datetime.time(9, 5), help_text="La hora (en zona horaria del servidor) a la que se liberarán las claves en cuarentena.", verbose_name="Hora de Reseteo de Cuarentena")),
                        ("last_quarantine_reset_date", models.DateField(default=datetime.date(2000, 1, 1), help_text="Registra el último día que se ejecutó el reseteo para asegurar que solo ocurra una vez al día.", verbose_name="Fecha del Último Reseteo de Cuarentena")),
                        ("seed_year", models.CharField(blank=True, help_text="El año académico específico (ej. 'Primero', 'Segundo') para acotar la generación.", max_length=20, verbose_name="Año Académico Semilla")),
                        ("last_run_timestamp", models.DateTimeField(blank=True, null=True, verbose_name="Última Ejecución")),
                        ("last_run_status", models.TextField(blank=True, verbose_name="Estado del Último Ciclo")),
                        ("event_log", models.JSONField(blank=True, default=list, verbose_name="Historial de Eventos del Motor")),
                        ("active_api_key", models.ForeignKey(blank=True, help_text="La clave que el sistema está utilizando actualmente para las generaciones.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="orchestrator.apikey", verbose_name="Clave de API Activa")),
                        ("seed_branch", models.ForeignKey(blank=True, help_text="La rama académica seleccionada como punto de partida para la generación.", null=True, on_delete=django.db.models.deletion.SET_NULL, to="academic_structure.branch", verbose_name="Rama Semilla")),
                        ("seed_degree", models.ForeignKey(blank=True, help_text="El grado académico seleccionado como punto de partida.", null=True, on_delete=django.db.models.deletion.SET_NULL, to="academic_structure.degree", verbose_name="Grado Semilla")),
                    ],
                    options={
                        "verbose_name": "Configuración del Centro de Control de Contenidos",
                        "verbose_name_plural": "C. Configuración del Centro de Control de Contenidos",
                        "db_table": "content_automation_automationsettings",
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
