# Generated by Django 5.0.7 on 2025-11-18 05:05

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "academic_structure",
            "0006_remove_subject_content_hash_contenthashfamily_and_more",
        ),
        ("contents", "0018_regenerate_topic_slugs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ej: 'Clave Primaria', 'Clave de Backup 1'",
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre Identificativo",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="La clave de API de Google Gemini.",
                        max_length=255,
                        unique=True,
                        verbose_name="Clave de API",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar para excluir esta clave de la rotación automática.",
                        verbose_name="¿Habilitada?",
                    ),
                ),
                (
                    "is_quarantined",
                    models.BooleanField(
                        default=False,
                        help_text="Marcado si la clave falla persistentemente. Una tarea diaria la liberará.",
                        verbose_name="En Cuarentena por Límite de Cuota",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clave de API de Gemini",
                "verbose_name_plural": "B. Claves de API de Gemini",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AutomationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_running",
                    models.BooleanField(
                        default=False,
                        help_text="Si está activado, la tarea 'always-on' buscará y procesará tareas pendientes.",
                        verbose_name="Interruptor Maestro de Automatización",
                    ),
                ),
                (
                    "quarantine_reset_time",
                    models.TimeField(
                        default=datetime.time(9, 5),
                        help_text="La hora (en zona horaria del servidor) a la que se liberarán las claves en cuarentena.",
                        verbose_name="Hora de Reseteo de Cuarentena",
                    ),
                ),
                (
                    "last_quarantine_reset_date",
                    models.DateField(
                        default=datetime.date(2000, 1, 1),
                        help_text="Registra el último día que se ejecutó el reseteo para asegurar que solo ocurra una vez al día.",
                        verbose_name="Fecha del Último Reseteo de Cuarentena",
                    ),
                ),
                (
                    "seed_year",
                    models.CharField(
                        blank=True,
                        help_text="El año académico específico (ej. 'Primero', 'Segundo') para acotar la generación.",
                        max_length=20,
                        verbose_name="Año Académico Semilla",
                    ),
                ),
                (
                    "last_run_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última Ejecución"
                    ),
                ),
                (
                    "last_run_status",
                    models.TextField(
                        blank=True, verbose_name="Estado del Último Ciclo"
                    ),
                ),
                (
                    "event_log",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Historial de Eventos del Motor",
                    ),
                ),
                (
                    "active_api_key",
                    models.ForeignKey(
                        blank=True,
                        help_text="La clave que el sistema está utilizando actualmente para las generaciones.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orchestrator.apikey",
                        verbose_name="Clave de API Activa",
                    ),
                ),
                (
                    "seed_branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="La rama académica seleccionada como punto de partida para la generación.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academic_structure.branch",
                        verbose_name="Rama Semilla",
                    ),
                ),
                (
                    "seed_degree",
                    models.ForeignKey(
                        blank=True,
                        help_text="El grado académico seleccionado como punto de partida.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academic_structure.degree",
                        verbose_name="Grado Semilla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del Centro de Control de Contenidos",
                "verbose_name_plural": "C. Configuración del Centro de Control de Contenidos",
            },
        ),
        migrations.CreateModel(
            name="ContentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente de Aprobación"),
                            ("APPROVED", "Aprobada para Automatización"),
                            ("IN_PROGRESS", "Generación en Proceso"),
                            ("FULFILLED", "Satisfecha"),
                            ("REJECTED", "Rechazada"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Estado de la Solicitud",
                    ),
                ),
                (
                    "requesters",
                    models.ManyToManyField(
                        related_name="content_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuarios Solicitantes",
                    ),
                ),
                (
                    "subject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_request",
                        to="academic_structure.subject",
                        verbose_name="Asignatura Solicitada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Contenido",
                "verbose_name_plural": "Solicitudes de Contenido",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FreeContentRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Título del Curso"),
                ),
                (
                    "detailed_prompt",
                    models.TextField(verbose_name="Descripción Detallada / Prompt"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("approved", "Aprobada"),
                            ("rejected", "Rechazada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado de la Solicitud",
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("similar_exists", "Contenido Similar Existente"),
                            ("ethics_violation", "Incumplimiento del Código Ético"),
                            ("offensive_content", "Contenido de Carácter Ofensivo"),
                            ("other", "Otro (ver notas)"),
                        ],
                        help_text="Visible solo si el estado es 'Rechazada'.",
                        max_length=30,
                        null=True,
                        verbose_name="Motivo del Rechazo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Solicitud"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="free_content_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario Solicitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Contenido Libre",
                "verbose_name_plural": "A. Solicitudes de Contenido Libre",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PendingContentTask",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "course_title",
                    models.CharField(
                        blank=True,
                        help_text="Proporcionar solo si es un curso libre.",
                        max_length=255,
                        verbose_name="Título del Curso (Curso Libre)",
                    ),
                ),
                (
                    "prompt_text",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada o prompt para generar un curso libre.",
                        verbose_name="Descripción/Prompt (Curso Libre)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("PROCESSING", "Procesando"),
                            ("COMPLETED", "Completada"),
                            ("FAILED", "Fallida (Manual)"),
                            ("FAILED_RETRYABLE", "Fallida (Reintentable)"),
                            ("FAILED_QUOTA", "Fallida (Límite de Cuota)"),
                            ("FAILED_FATAL", "Fallida (Fatal)"),
                            ("PAUSED", "Pausado por el Administrador"),
                        ],
                        default="PENDING",
                        max_length=30,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "task_origin",
                    models.CharField(
                        choices=[
                            ("MASS_GENERATION", "Masivo"),
                            ("APPROVED_REQUEST", "Solicitud Aprobada"),
                            ("MANUAL_CREATION", "Creación Manual"),
                            ("SYSTEM_RESTART", "Reinicio por Fallo"),
                        ],
                        default="MANUAL_CREATION",
                        max_length=30,
                        verbose_name="Origen de la Tarea",
                    ),
                ),
                (
                    "api_key_used",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Clave de API Utilizada",
                    ),
                ),
                (
                    "section_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Número de Secciones"
                    ),
                ),
                (
                    "structured_content",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Almacena artefactos intermedios como el temario o las secciones generadas.",
                        null=True,
                        verbose_name="Contenido Estructurado (JSON)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notas adicionales"),
                ),
                (
                    "log_file_path",
                    models.CharField(
                        blank=True,
                        help_text="Ruta al archivo de log detallado de la tarea.",
                        max_length=512,
                        null=True,
                        verbose_name="Ruta al Archivo de Log",
                    ),
                ),
                (
                    "task_log",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Registro de eventos y pasos de la tarea.",
                        verbose_name="Log de Tarea",
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, null=True, verbose_name="Último Error Fatal"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_content_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asignado a",
                    ),
                ),
                (
                    "content_material",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_task",
                        to="contents.contentmaterial",
                        verbose_name="Material de Contenido Resultante",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        help_text="Asignar solo si es un curso derivado de una asignatura académica.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_tasks",
                        to="academic_structure.subject",
                        verbose_name="Asignatura (Curso Académico)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea de Automatización de Contenido",
                "verbose_name_plural": "Tareas de Automatización de Contenido",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedContentChunk",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="El número de orden para reconstruir el documento final.",
                        verbose_name="Orden de Sección",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="El texto generado por la IA para esta sección.",
                        verbose_name="Contenido de la Sección",
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este fragmento ya ha sido incluido en el ContenidoMaterial final.",
                        verbose_name="¿Procesado e incluido?",
                    ),
                ),
                (
                    "ai_sources",
                    models.TextField(
                        blank=True, null=True, verbose_name="Fuentes de la IA"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_chunks",
                        to="orchestrator.pendingcontenttask",
                        verbose_name="Tarea Asociada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fragmento de Contenido Generado",
                "verbose_name_plural": "Fragmentos de Contenido Generado",
                "ordering": ["task", "order"],
                "unique_together": {("task", "order")},
            },
        ),
    ]
