# Generated by Django 5.0.7 on 2025-11-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orchestrator", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="apikey",
            table=None,
        ),
        migrations.AlterModelTable(
            name="automationsettings",
            table=None,
        ),
    ]
