# Generated by Django 5.0.7 on 2025-11-18 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academic_structure",
            "0006_remove_subject_content_hash_contenthashfamily_and_more",
        ),
        ("contents", "0018_regenerate_topic_slugs"),
        ("orchestrator", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pendingcontenttask",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(
                        ("status__in", ["COMPLETED", "FAILED", "FAILED_FATAL"]),
                        _negated=True,
                    ),
                    ("subject__isnull", False),
                ),
                fields=("subject",),
                name="unique_active_academic_task_per_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="pendingcontenttask",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(
                        ("status__in", ["COMPLETED", "FAILED", "FAILED_FATAL"]),
                        _negated=True,
                    ),
                    ("subject__isnull", True),
                ),
                fields=("course_title",),
                name="unique_active_free_task_per_title",
            ),
        ),
        migrations.AddConstraint(
            model_name="pendingcontenttask",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("subject__isnull", False),
                        ("course_title__exact", ""),
                        ("prompt_text__exact", ""),
                    ),
                    models.Q(
                        ("subject__isnull", True),
                        models.Q(("course_title__exact", ""), _negated=True),
                        models.Q(("prompt_text__exact", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="task_type_is_exclusive",
            ),
        ),
    ]
