# Generated by Django 5.0.7 on 2025-12-08 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orchestrator",
            "0002_pendingcontenttask_unique_active_academic_task_per_subject_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingcontenttask",
            name="consecutive_api_errors",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Contador de fallos seguidos en llamadas a la API. Se usa para la lógica de reintento exponencial o aborto.",
                verbose_name="Errores Consecutivos de API",
            ),
        ),
        migrations.AddField(
            model_name="pendingcontenttask",
            name="current_step",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Puntero para reanudar la generación en el punto exacto (ej: índice del temario).",
                verbose_name="Paso Actual de Ejecución",
            ),
        ),
        migrations.AddField(
            model_name="pendingcontenttask",
            name="global_actuation_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Fusible físico. Cuenta las veces que el orquestador ha intentado procesar esta tarea. Si supera el límite, se aborta.",
                verbose_name="Contador Global de Actuaciones",
            ),
        ),
        migrations.AddField(
            model_name="pendingcontenttask",
            name="last_api_error_at",
            field=models.DateTimeField(
                blank=True,
                help_text='Timestamp del último fallo de API para calcular ventanas de "amnistía".',
                null=True,
                verbose_name="Momento del Último Error de API",
            ),
        ),
        migrations.AddField(
            model_name="pendingcontenttask",
            name="last_error_api_key",
            field=models.ForeignKey(
                blank=True,
                help_text="La clave que provocó el último error, para evitar culpar a nuevas claves.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="failed_tasks",
                to="orchestrator.apikey",
                verbose_name="Última Clave de API Fallida",
            ),
        ),
        migrations.AddField(
            model_name="pendingcontenttask",
            name="last_heartbeat",
            field=models.DateTimeField(
                blank=True,
                help_text='Marca de tiempo para detectar tareas "zombies" que murieron silenciosamente.',
                null=True,
                verbose_name="Último Latido (Heartbeat)",
            ),
        ),
    ]
