# Generated by Django 5.0.7 on 2025-12-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestrator", "0003_pendingcontenttask_consecutive_api_errors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationsettings",
            name="max_consecutive_api_errors",
            field=models.PositiveIntegerField(
                default=4,
                help_text="(Fusible de Cuota) Número de fallos de API seguidos en una misma sección antes de poner la clave en cuarentena.",
                verbose_name="Umbral de Errores de API Consecutivos",
            ),
        ),
        migrations.AddField(
            model_name="automationsettings",
            name="max_task_actuations",
            field=models.PositiveIntegerField(
                default=20,
                help_text="(Fusible Global) Número máximo de veces que el orquestador intentará iniciar una misma tarea antes de marcarla como fallo fatal.",
                verbose_name="Umbral de Actuaciones Máximas por Tarea",
            ),
        ),
        migrations.AddField(
            model_name="automationsettings",
            name="zombie_task_threshold_hours",
            field=models.PositiveIntegerField(
                default=24,
                help_text="Número de horas de inactividad para que una tarea 'procesando' sea considerada zombie y purgada.",
                verbose_name="Umbral de Horas para Tareas Zombie",
            ),
        ),
    ]
