# Generated by Django 5.0.7 on 2025-12-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestrator", "0004_automationsettings_max_consecutive_api_errors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="consecutive_failures",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Contador de errores de cuota (ResourceExhausted) para gestionar la cuarentena.",
                verbose_name="Fallos Consecutivos",
            ),
        ),
    ]
