# Generated by Django 5.0.7 on 2025-12-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestrator", "0005_apikey_consecutive_failures"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationsettings",
            name="is_mass_generation_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Si está desactivado, el sistema solo procesará solicitudes de usuarios y evaluaciones, ignorando el relleno automático.",
                verbose_name="Generación Masiva Activa",
            ),
        ),
    ]
