# Generated by Django 5.0.7 on 2025-10-08 18:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "annotation_type",
                    models.CharField(
                        choices=[
                            ("highlight", "Subrayado"),
                            ("note", "Nota"),
                            ("mark", "Marcado"),
                        ],
                        help_text="Tipo de anotación (subrayado, nota, marcado).",
                        max_length=20,
                        verbose_name="Tipo de Anotación",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Texto de la anotación (para tipo 'nota') o el texto del DOM seleccionado (para 'subrayado', 'marcado').",
                        verbose_name="Contenido",
                    ),
                ),
                (
                    "selected_text",
                    models.TextField(
                        blank=True,
                        help_text="El texto exacto seleccionado del DOM al que se refiere esta anotación (importante para notas con referencia).",
                        null=True,
                        verbose_name="Texto Seleccionado del DOM",
                    ),
                ),
                (
                    "position",
                    models.TextField(
                        help_text="Información de posición en el documento (formato JSON).",
                        verbose_name="Posición",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        help_text="Color de la anotación en formato hexadecimal o nombre de color CSS.",
                        max_length=20,
                        verbose_name="Color",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sala de Estudio - Anotación",
                "verbose_name_plural": "F. Sala de Estudio - Anotaciones",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentCopy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "html_content",
                    models.TextField(
                        help_text="El cuerpo del contenido con las anotaciones y marcados integrados.",
                        verbose_name="Contenido con Anotaciones (HTML)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Marca esta casilla si quieres que esta copia sea visible para todos los usuarios. Si no, solo tú podrás verla.",
                        verbose_name="¿Es público?",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sala de Estudio - Copia",
                "verbose_name_plural": "E. Sala de Estudio - Copias",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=512, verbose_name="Título del Curso"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default="", max_length=600, unique=True
                    ),
                ),
                (
                    "short_description",
                    models.TextField(verbose_name="Descripción Corta"),
                ),
                (
                    "markdown_content",
                    models.TextField(verbose_name="Contenido (Markdown)"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="¿Es Público?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Material de Contenido",
                "verbose_name_plural": "D. Materiales de Contenido",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la Disciplina"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default="", max_length=300, unique=True
                    ),
                ),
                (
                    "has_free_content",
                    models.BooleanField(
                        default=False, verbose_name="Tiene Contenido Libre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Disciplina",
                "verbose_name_plural": "2. Disciplinas",
                "ordering": ["knowledge_area", "name"],
            },
        ),
        migrations.CreateModel(
            name="FavoriteFolder",
            fields=[
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la Carpeta"
                    ),
                ),
                (
                    "folder_type",
                    models.CharField(
                        choices=[
                            ("FAV", "Mis Favoritos"),
                            ("PUB", "Mis Publicaciones"),
                            ("USR", "Carpeta de Usuario"),
                        ],
                        default="USR",
                        max_length=3,
                        verbose_name="Tipo de Carpeta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carpeta de Favoritos",
                "verbose_name_plural": "G. Carpetas de Favoritos",
                "ordering": ["path"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nombre del Área"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default="", max_length=300, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "has_free_content",
                    models.BooleanField(
                        default=False, verbose_name="Tiene Contenido Libre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Área de Conocimiento",
                "verbose_name_plural": "1. Áreas de Conocimiento",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MainCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la Categoría"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default="", max_length=300, unique=True
                    ),
                ),
                (
                    "has_free_content",
                    models.BooleanField(
                        default=False, verbose_name="Tiene Contenido Libre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría Principal",
                "verbose_name_plural": "3. Categorías Principales",
                "ordering": ["discipline", "name"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nombre del Tema"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default="", max_length=300, unique=True
                    ),
                ),
                (
                    "has_free_content",
                    models.BooleanField(
                        default=False, verbose_name="Tiene Contenido Libre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tema",
                "verbose_name_plural": "4. Temas (Jerarquía)",
                "ordering": ["name"],
            },
        ),
    ]
