# Generated by Django 5.0.7 on 2025-10-08 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic_structure", "0001_initial"),
        ("contents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="user",
            field=models.ForeignKey(
                help_text="Usuario que creó esta anotación.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_annotations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario Creador",
            ),
        ),
        migrations.AddField(
            model_name="contentcopy",
            name="user",
            field=models.ForeignKey(
                help_text="Usuario que ha creado esta copia personalizada.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_copies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="copy",
            field=models.ForeignKey(
                help_text="Copia de contenido a la que pertenece esta anotación.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="contents.contentcopy",
                verbose_name="Copia de Contenido",
            ),
        ),
        migrations.AddField(
            model_name="contentmaterial",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_content",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contentmaterial",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_materials",
                to="academic_structure.subject",
                verbose_name="Asignatura Académica Asociada",
            ),
        ),
        migrations.AddField(
            model_name="contentcopy",
            name="original_content",
            field=models.ForeignKey(
                help_text="Contenido original del que se deriva esta copia.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="derived_copies",
                to="contents.contentmaterial",
                verbose_name="Contenido Original",
            ),
        ),
        migrations.AddField(
            model_name="favoritefolder",
            name="materials",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_folders",
                to="contents.contentmaterial",
                verbose_name="Materiales Favoritos",
            ),
        ),
        migrations.AddField(
            model_name="favoritefolder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_folders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="discipline",
            name="knowledge_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disciplines",
                to="contents.knowledgearea",
                verbose_name="Área de Conocimiento",
            ),
        ),
        migrations.AddField(
            model_name="maincategory",
            name="discipline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_categories",
                to="contents.discipline",
                verbose_name="Disciplina",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="main_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Asignar solo si este es un tema de primer nivel.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="root_topics",
                to="contents.maincategory",
                verbose_name="Categoría Principal Raíz",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Asignar si este es un sub-tema de otro tema.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtopics",
                to="contents.topic",
                verbose_name="Tema Padre",
            ),
        ),
        migrations.AddField(
            model_name="contentmaterial",
            name="topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="content_materials",
                to="contents.topic",
                verbose_name="Clasificación (Tema Específico)",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contentcopy",
            unique_together={("original_content", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="favoritefolder",
            unique_together={("user", "folder_type")},
        ),
        migrations.AlterUniqueTogether(
            name="discipline",
            unique_together={("knowledge_area", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="maincategory",
            unique_together={("discipline", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="topic",
            unique_together={("parent", "name")},
        ),
    ]
