# Generated by Django 5.0.7 on 2025-10-11 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favoritefolder",
            unique_together=set(),
        ),
    ]
