# Generated by Django 5.0.7 on 2025-10-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academic_structure",
            "0005_alter_subject_options_alter_subject_unique_together_and_more",
        ),
        ("contents", "0003_alter_favoritefolder_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentmaterial",
            name="subject",
        ),
        migrations.AddField(
            model_name="contentmaterial",
            name="subject",
            field=models.ManyToManyField(
                blank=True,
                related_name="content_materials",
                to="academic_structure.subject",
                verbose_name="Asignaturas Académicas Asociadas",
            ),
        ),
    ]
