# Generated by Django 5.0.7 on 2025-11-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0004_remove_contentmaterial_subject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentmaterial",
            name="is_free_content",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Es Contenido Libre"
            ),
        ),
    ]
