# Generated by Django 5.0.7 on 2025-11-04 12:45

from django.db import migrations
from django.db.models import Q

def apply_public_status_rules(apps, schema_editor):
    """
    Aplica retroactivamente las reglas de negocio para forzar la visibilidad
    pública del contenido académico y del contenido libre creado por el staff.
    """
    ContentMaterial = apps.get_model("contents", "ContentMaterial")
    
    # Se seleccionan todos los materiales que cumplen una de las dos condiciones
    # y que actualmente no son públicos, para actualizarlos.
    materials_to_update = ContentMaterial.objects.filter(
        Q(is_public=False) & 
        (Q(subject__isnull=False) | Q(is_free_content=True, creator__is_staff=True))
    ).distinct()

    count = materials_to_update.update(is_public=True)

    if count > 0:
        # Este mensaje aparecerá en la consola al ejecutar las migraciones
        print(f"\n  Se han actualizado {count} materiales a 'público' para cumplir las nuevas reglas de negocio.")

def reverse_func(apps, schema_editor):
    """
    Función de reversión. Se deja vacía intencionadamente ya que no hay un
    estado previo claro y seguro al que revertir esta lógica de negocio.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0005_contentmaterial_is_free_content"),
        # Dependencia explícita de 'users' para poder consultar 'creator__is_staff'
        ("users", "0001_initial"), 
    ]

    operations = [
        migrations.RunPython(apply_public_status_rules, reverse_func),
    ]
