# Generated by Django 5.0.7 on 2025-11-05 14:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academic_structure",
            "0006_remove_subject_content_hash_contenthashfamily_and_more",
        ),
        ("contents", "0006_update_public_status_by_rules"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeContentCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        verbose_name="Nombre de la Categoría de Contenido Libre",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default="", max_length=300, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de Contenido Libre",
                "verbose_name_plural": "B. Categorías de Contenido Libre (Nivel 2)",
                "ordering": ["topic", "name"],
            },
        ),
        migrations.CreateModel(
            name="FreeContentTopic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Nombre del Tema de Contenido Libre",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default="", max_length=300, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Tema de Contenido Libre",
                "verbose_name_plural": "A. Temas de Contenido Libre (Nivel 1)",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="contentmaterial",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                help_text="Usar solo para contenido académico estructurado.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="content_materials",
                to="contents.topic",
                verbose_name="Clasificación Académica",
            ),
        ),
        migrations.AddField(
            model_name="contentmaterial",
            name="free_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Usar solo para contenido libre no estructurado.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="content_materials",
                to="contents.freecontentcategory",
                verbose_name="Clasificación de Contenido Libre",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentmaterial",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("is_free_content", True),
                        ("free_category__isnull", False),
                        ("topic__isnull", True),
                    ),
                    models.Q(
                        ("is_free_content", False),
                        ("free_category__isnull", True),
                        ("topic__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="content_hierarchy_is_exclusive",
            ),
        ),
        migrations.AddField(
            model_name="freecontentcategory",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="contents.freecontenttopic",
                verbose_name="Tema Padre",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="freecontentcategory",
            unique_together={("topic", "name")},
        ),
    ]
