# /home/MiguelAeTxio/CampuStudiOnline/contents/migrations/0009_populate_free_content_hierarchy.py
# Generated by Django 5.0.7 on 2025-11-05 15:15

from django.db import migrations
from django.utils.text import slugify

HIERARCHY_DATA = {
    "Historia de la Música": [
        "Música Clásica", "Jazz", "Rock", "Pop", "Electrónica",
        "Música del Mundo", "Blues", "Folk", "Rock Progresivo", "Jazz Fusión"
    ],
    "Formación Profesional": [
        "Administración y Gestión", "Informática y Comunicaciones",
        "Electricidad y Electrónica", "Sanidad", "Hostelería y Turismo",
        "Imagen y Sonido", "Mecánica", "Comercio y Marketing"
    ]
}

def populate_hierarchy(apps, schema_editor):
    """
    Puebla la nueva jerarquía de contenido libre con los datos iniciales.
    """
    FreeContentTopic = apps.get_model('contents', 'FreeContentTopic')
    FreeContentCategory = apps.get_model('contents', 'FreeContentCategory')

    print("\n") # Salto de línea para claridad

    for topic_name, categories in HIERARCHY_DATA.items():
        # Crear el Tópico de Nivel 1 (si no existe)
        topic_obj, created = FreeContentTopic.objects.get_or_create(
            name=topic_name,
            defaults={'slug': slugify(topic_name)}
        )
        if created:
            print(f"  > Creado FreeContentTopic: '{topic_name}'")

        # Crear las Categorías de Nivel 2 asociadas (si no existen)
        for category_name in categories:
            # Replicamos la lógica de generación de slug del modelo para consistencia
            base_slug = slugify(f"{topic_name}-{category_name}")
            
            # Usamos get_or_create para la idempotencia
            cat_obj, created = FreeContentCategory.objects.get_or_create(
                topic=topic_obj,
                name=category_name,
                defaults={'slug': base_slug}
            )
            if created:
                print(f"    - Creada FreeContentCategory: '{category_name}'")

    print("\n  > Jerarquía de contenido libre poblada/verificada exitosamente.")


def revert_hierarchy(apps, schema_editor):
    """
    Elimina los datos creados por esta migración. La eliminación en cascada se encarga de las categorías.
    """
    FreeContentTopic = apps.get_model('contents', 'FreeContentTopic')
    
    # Simplemente eliminamos los Tópicos de Nivel 1; las categorías se borrarán en cascada.
    deleted_count, _ = FreeContentTopic.objects.filter(name__in=HIERARCHY_DATA.keys()).delete()
    
    if deleted_count > 0:
        print(f"\n  > Eliminados {deleted_count} Tópicos de contenido libre y sus categorías asociadas.")


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_freecontentcategory_freecontenttopic_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_hierarchy, reverse_code=revert_hierarchy),
    ]
