# Generated by Django 5.0.7 on 2025-11-05 17:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0009_populate_free_content_hierarchy"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeContentMasterCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Nombre de la Categoría Maestra",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default="", max_length=300, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Orden de Visualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría Maestra de Contenido Libre",
                "verbose_name_plural": "A. Categorías Maestras de Contenido Libre",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="freecontentcategory",
            options={
                "ordering": ["topic", "name"],
                "verbose_name": "Categoría de Contenido Libre (Legacy)",
                "verbose_name_plural": "C. Categorías de Contenido Libre (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="freecontenttopic",
            options={
                "ordering": ["name"],
                "verbose_name": "Tema de Contenido Libre (Legacy)",
                "verbose_name_plural": "B. Temas de Contenido Libre (Legacy)",
            },
        ),
    ]
