# Generated by Django 4.2.14 on 2025-11-05 18:10

from django.db import migrations
from django.utils.text import slugify

# Definimos las categorías maestras que deben existir permanentemente.
# El display_order define su aparición en la UI.
MASTER_CATEGORIES = [
    {"name": "Historia de la Música", "display_order": 10},
    {"name": "Biografías", "display_order": 20},
    {"name": "Formación Profesional", "display_order": 30},
    {"name": "Desarrollo Personal", "display_order": 40},
    {"name": "General", "display_order": 50},
]

def populate_categories(apps, schema_editor):
    """
    Crea las instancias de FreeContentMasterCategory. Se usa update_or_create
    para que la migración sea segura de ejecutar múltiples veces (idempotente).
    """
    FreeContentMasterCategory = apps.get_model('contents', 'FreeContentMasterCategory')
    
    for category_data in MASTER_CATEGORIES:
        FreeContentMasterCategory.objects.update_or_create(
            name=category_data["name"],
            defaults={
                "slug": slugify(category_data["name"]),
                "display_order": category_data["display_order"],
            }
        )

def unpopulate_categories(apps, schema_editor):
    """
    Elimina las instancias creadas, permitiendo que la migración sea reversible.
    """
    FreeContentMasterCategory = apps.get_model('contents', 'FreeContentMasterCategory')
    category_names = [d['name'] for d in MASTER_CATEGORIES]
    FreeContentMasterCategory.objects.filter(name__in=category_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_freecontentmastercategory_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_categories, reverse_code=unpopulate_categories),
    ]
