# Generated by Django 5.0.7 on 2025-11-05 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0011_populate_master_categories"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contentmaterial",
            name="content_hierarchy_is_exclusive",
        ),
        migrations.AddField(
            model_name="contentmaterial",
            name="master_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Asignar solo para contenido libre.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="content_materials",
                to="contents.freecontentmastercategory",
                verbose_name="Clasificación Maestra de Contenido Libre",
            ),
        ),
        migrations.AlterField(
            model_name="contentmaterial",
            name="free_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Usar solo para contenido libre no estructurado.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="content_materials",
                to="contents.freecontentcategory",
                verbose_name="Clasificación de Contenido Libre (Legacy)",
            ),
        ),
    ]
