# Generated by Django 4.2.14 on 2025-11-05 18:30

from django.db import migrations

def migrate_to_master_category(apps, schema_editor):
    """
    Transfiere la categorización de los ContentMaterial de la jerarquía legacy
    (FreeContentTopic -> FreeContentCategory) a la nueva ForeignKey directa
    hacia FreeContentMasterCategory.
    """
    ContentMaterial = apps.get_model('contents', 'ContentMaterial')
    FreeContentMasterCategory = apps.get_model('contents', 'FreeContentMasterCategory')

    # Iteramos solo sobre el contenido libre que AÚN NO ha sido migrado
    # y que tiene una categoría legacy asignada.
    materials_to_migrate = ContentMaterial.objects.filter(
        is_free_content=True,
        master_category__isnull=True,
        free_category__isnull=False
    ).select_related('free_category__topic')

    for material in materials_to_migrate:
        # El nombre de la categoría maestra se deriva del antiguo 'FreeContentTopic'
        if not material.free_category or not material.free_category.topic:
            continue
            
        legacy_topic_name = material.free_category.topic.name
        
        try:
            # Buscamos la categoría maestra correspondiente por el nombre
            master_category = FreeContentMasterCategory.objects.get(name=legacy_topic_name)
            
            # Asignamos la nueva categoría y guardamos
            material.master_category = master_category
            material.save(update_fields=['master_category'])

        except FreeContentMasterCategory.DoesNotExist:
            # Esta es una salvaguarda. Si una categoría maestra no existe
            # (lo cual no debería pasar gracias a la migración de datos anterior),
            # dejamos un mensaje y continuamos, sin asignar nada.
            print(f"\n[ADVERTENCIA] No se encontró una FreeContentMasterCategory con el nombre '{legacy_topic_name}'. "
                  f"El material '{material.title}' (ID: {material.pk}) no fue migrado.")

def reverse_migration(apps, schema_editor):
    """
    Revierte la migración estableciendo master_category a NULL para el contenido libre.
    No se intenta reconstruir la relación legacy, ya que esa estructura será eliminada.
    """
    ContentMaterial = apps.get_model('contents', 'ContentMaterial')
    ContentMaterial.objects.filter(is_free_content=True).update(master_category=None)


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0012_remove_contentmaterial_content_hierarchy_is_exclusive_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_to_master_category, reverse_code=reverse_migration),
    ]
