# Generated by Django 5.0.7 on 2025-11-05 18:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0013_data_migration_to_master_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="freecontentmastercategory",
            options={
                "ordering": ["display_order", "name"],
                "verbose_name": "Categoría Maestra de Contenido Libre",
                "verbose_name_plural": "A. Categorías Maestras (Nivel 1)",
            },
        ),
        migrations.CreateModel(
            name="FreeContentSubCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la Subcategoría"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default="", max_length=300, unique=True
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Orden de Visualización"
                    ),
                ),
                (
                    "master_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_categories",
                        to="contents.freecontentmastercategory",
                        verbose_name="Categoría Maestra Padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcategoría de Contenido Libre",
                "verbose_name_plural": "A.1. Subcategorías (Nivel 2)",
                "ordering": ["master_category", "display_order", "name"],
                "unique_together": {("master_category", "name")},
            },
        ),
    ]
