# Generated by Django 5.0.7 on 2025-11-05 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academic_structure",
            "0006_remove_subject_content_hash_contenthashfamily_and_more",
        ),
        ("contents", "0014_alter_freecontentmastercategory_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contentmaterial",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Asignar solo si el contenido pertenece a una subcategoría específica.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="content_materials",
                to="contents.freecontentsubcategory",
                verbose_name="Subcategoría (Nivel 2)",
            ),
        ),
        migrations.AlterField(
            model_name="contentmaterial",
            name="master_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Asignar solo para contenido libre.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="content_materials",
                to="contents.freecontentmastercategory",
                verbose_name="Categoría Maestra (Nivel 1)",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentmaterial",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("is_free_content", True),
                        ("master_category__isnull", False),
                        ("topic__isnull", True),
                    ),
                    models.Q(
                        ("is_free_content", False),
                        ("master_category__isnull", True),
                        ("topic__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="content_hierarchy_is_exclusive",
            ),
        ),
    ]
