# Generated by Django 4.2.14 on 2025-11-05 19:12

from django.db import migrations
from django.utils.text import slugify

# Estructura de datos que define la jerarquía de subcategorías maestras.
SUBCATEGORY_DATA = {
    "Historia de la Música": [
        {"name": "Música Clásica", "order": 10},
        {"name": "Jazz", "order": 20},
        {"name": "Rock and Roll", "order": 30},
        {"name": "Rock Progresivo", "order": 40},
        {"name": "Heavy Metal", "order": 50},
        {"name": "Pop", "order": 60},
        {"name": "Electrónica", "order": 70},
    ],
    "Formación Profesional": [
        {"name": "Administración y Gestión", "order": 10},
        {"name": "Comercio y Marketing", "order": 20},
        {"name": "Electricidad y Electrónica", "order": 30},
        {"name": "Hostelería y Turismo", "order": 40},
        {"name": "Informática y Comunicaciones", "order": 50},
        {"name": "Mecánica", "order": 60},
        {"name": "Sanidad", "order": 70},
    ],
}

def populate_subcategories(apps, schema_editor):
    """
    Crea las instancias de FreeContentSubCategory basándose en la estructura de datos.
    """
    FreeContentMasterCategory = apps.get_model('contents', 'FreeContentMasterCategory')
    FreeContentSubCategory = apps.get_model('contents', 'FreeContentSubCategory')

    for master_name, sub_list in SUBCATEGORY_DATA.items():
        try:
            master_category = FreeContentMasterCategory.objects.get(name=master_name)
            for sub_data in sub_list:
                # CORRECCIÓN: Generar el slug explícitamente dentro de la migración.
                base_slug = slugify(f"{master_category.name}-{sub_data['name']}")
                proposed_slug = base_slug
                counter = 1
                while FreeContentSubCategory.objects.filter(slug=proposed_slug).exists():
                    proposed_slug = f"{base_slug}-{counter}"
                    counter += 1

                FreeContentSubCategory.objects.update_or_create(
                    master_category=master_category,
                    name=sub_data["name"],
                    defaults={
                        "display_order": sub_data["order"],
                        "slug": proposed_slug
                    }
                )
        except FreeContentMasterCategory.DoesNotExist:
            print(f"\n[ADVERTENCIA] La categoría maestra '{master_name}' no existe. "
                  f"No se pudieron crear sus subcategorías.")

def unpopulate_subcategories(apps, schema_editor):
    """
    Elimina las subcategorías creadas para que la migración sea reversible.
    """
    FreeContentSubCategory = apps.get_model('contents', 'FreeContentSubCategory')
    sub_names_to_delete = []
    for sub_list in SUBCATEGORY_DATA.values():
        for sub_data in sub_list:
            sub_names_to_delete.append(sub_data["name"])
    
    FreeContentSubCategory.objects.filter(name__in=sub_names_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0015_contentmaterial_sub_category_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_subcategories, reverse_code=unpopulate_subcategories),
    ]
