# Generated by Django 5.0.7 on 2025-11-13 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academic_structure",
            "0006_remove_subject_content_hash_contenthashfamily_and_more",
        ),
        ("contents", "0016_populate_sub_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contentcopy",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="contentcopy",
            name="subject_context",
            field=models.ForeignKey(
                blank=True,
                help_text="Asignatura específica para la cual se creó esta copia de estudio.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="study_copies",
                to="academic_structure.subject",
                verbose_name="Asignatura de Contexto",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contentcopy",
            unique_together={("original_content", "user", "subject_context")},
        ),
    ]
