# Generated by Django 5.0.7 on 2025-11-22 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0018_regenerate_topic_slugs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # 1. LO QUE SE EJECUTA EN LA BASE DE DATOS (Solo crear lo nuevo)
            database_operations=[
                migrations.CreateModel(
                    name="UserStudyNavigation",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "navigation_tree",
                            models.JSONField(
                                default=dict,
                                help_text="Estructura jerárquica pre-calculada de las copias del usuario.",
                                verbose_name="Árbol de Navegación (JSON)",
                            ),
                        ),
                        (
                            "last_updated",
                            models.DateTimeField(
                                auto_now=True, verbose_name="Última Actualización"
                            ),
                        ),
                        (
                            "user",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="study_navigation",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Usuario",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Navegación de Sala de Estudio",
                        "verbose_name_plural": "Navegaciones de Sala de Estudio",
                    },
                ),
            ],
            # 2. LO QUE DJANGO CREE QUE PASÓ (Todo: borrados y creaciones)
            state_operations=[
                migrations.CreateModel(
                    name="UserStudyNavigation",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "navigation_tree",
                            models.JSONField(
                                default=dict,
                                help_text="Estructura jerárquica pre-calculada de las copias del usuario.",
                                verbose_name="Árbol de Navegación (JSON)",
                            ),
                        ),
                        (
                            "last_updated",
                            models.DateTimeField(
                                auto_now=True, verbose_name="Última Actualización"
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Navegación de Sala de Estudio",
                        "verbose_name_plural": "Navegaciones de Sala de Estudio",
                    },
                ),
                migrations.AddField(
                    model_name="userstudynavigation",
                    name="user",
                    field=models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_navigation",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                migrations.RemoveConstraint(
                    model_name="contentmaterial",
                    name="content_hierarchy_is_exclusive",
                ),
                migrations.RemoveField(
                    model_name="contentmaterial",
                    name="free_category",
                ),
                migrations.RemoveField(
                    model_name="contentmaterial",
                    name="topic",
                ),
                migrations.DeleteModel(
                    name="KnowledgeArea",
                ),
                migrations.DeleteModel(
                    name="Discipline",
                ),
                migrations.DeleteModel(
                    name="FreeContentTopic",
                ),
                migrations.DeleteModel(
                    name="FreeContentCategory",
                ),
                migrations.DeleteModel(
                    name="MainCategory",
                ),
                migrations.DeleteModel(
                    name="Topic",
                ),
            ]
        )
    ]
