# Generated by Django 5.0.7 on 2026-02-23 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contents",
            "0019_userstudynavigation_alter_discipline_unique_together_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstudynavigation",
            name="user",
            field=models.OneToOneField(
                help_text="Usuario propietario de este árbol de navegación. Se elimina en cascada.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_navigation",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
    ]
