# Generated by Django 5.0.7 on 2026-02-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0020_alter_userstudynavigation_user"),
    ]

    operations = []
