# Generated by Django 5.0.7 on 2025-10-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente de Generación"),
                            ("PROCESSING", "Procesando Generación"),
                            ("COMPLETED", "Lista para Realizar"),
                            ("EXPIRED_UNTAKEN", "Expirada (No Realizada)"),
                            ("CORRECTING", "Corrigiendo"),
                            ("RESULTS_AVAILABLE", "Resultados Disponibles"),
                            ("CORRECTION_EXPIRED", "Corrección Expirada"),
                            ("FAILED", "Fallida (Error General)"),
                            ("TIMEOUT_FAILURE", "Fallo por Tiempo de Espera"),
                            ("GENERATION_FAILURE", "Fallo de Generación"),
                            ("USER_CANCELLED", "Cancelada por el Usuario"),
                        ],
                        default="PENDING",
                        max_length=30,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "total_questions_expected",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The total number of sections detected that will be converted into questions.",
                        verbose_name="Total de preguntas esperadas",
                    ),
                ),
                (
                    "questions_processed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The number of questions that the worker has already generated.",
                        verbose_name="Preguntas procesadas",
                    ),
                ),
                (
                    "was_viewed",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the user has viewed the results of this correction to avoid penalization.",
                        verbose_name="Corrección Vista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación",
                "verbose_name_plural": "Evaluaciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(verbose_name="Texto de la Pregunta"),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("open_ended", "Respuesta Abierta"),
                            ("multiple_choice", "Opción Múltiple"),
                        ],
                        default="open_ended",
                        max_length=20,
                        verbose_name="Tipo de Pregunta",
                    ),
                ),
                (
                    "model_answer",
                    models.TextField(
                        help_text="The ideal answer that will be used as a reference for correction.",
                        verbose_name="Respuesta Modelo (Generada por IA)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta",
                "verbose_name_plural": "Preguntas",
                "ordering": ["assessment", "id"],
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_text",
                    models.TextField(verbose_name="Texto de la Respuesta del Usuario"),
                ),
                (
                    "answered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Respondido En"
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        help_text="The assigned score, e.g., from 0.0 to 10.0.",
                        null=True,
                        verbose_name="Puntuación",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True,
                        help_text="Comments or corrections generated by the AI.",
                        verbose_name="Comentarios",
                    ),
                ),
                (
                    "correction_expiration_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de Expiración de la Corrección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta del Usuario",
                "verbose_name_plural": "Respuestas del Usuario",
                "ordering": ["-answered_at"],
            },
        ),
    ]
