# Generated by Django 5.0.7 on 2025-10-26 12:16

from django.db import migrations

def populate_content_copy_forward(apps, schema_editor):
    """
    Popula el nuevo campo 'content_copy' en el modelo Assessment.
    Para cada Assessment, encuentra el ContentCopy correspondiente basándose en el
    usuario y el contenido original. Si no se encuentra ContentCopy, el Assessment
    es un huérfano y debe ser eliminado para garantizar la integridad de los datos.
    """
    Assessment = apps.get_model('assessment', 'Assessment')
    ContentCopy = apps.get_model('contents', 'ContentCopy')

    assessments_to_update = []
    assessments_to_delete_ids = []

    # Itera sobre todas las evaluaciones para encontrar su content_copy correspondiente
    for assessment in Assessment.objects.all():
        try:
            # Usamos _id para ser más eficientes y evitar joins innecesarios
            content_copy = ContentCopy.objects.get(
                original_content_id=assessment.content_id,
                user_id=assessment.user_id
            )
            assessment.content_copy = content_copy
            assessments_to_update.append(assessment)
        except ContentCopy.DoesNotExist:
            # Este assessment es un huérfano, se marca para eliminación
            assessments_to_delete_ids.append(assessment.id)

    # Realiza la actualización en bloque por eficiencia
    if assessments_to_update:
        print(f"\\n  -> Actualizando {len(assessments_to_update)} evaluaciones con su ContentCopy correspondiente.")
        Assessment.objects.bulk_update(assessments_to_update, ['content_copy'])

    # Realiza la eliminación en bloque de los huérfanos
    if assessments_to_delete_ids:
        print(f"\\n  -> Eliminando {len(assessments_to_delete_ids)} evaluaciones huérfanas: {assessments_to_delete_ids}")
        Assessment.objects.filter(id__in=assessments_to_delete_ids).delete()


def populate_content_copy_backward(apps, schema_editor):
    """
    Operación inversa: simplemente anula el campo 'content_copy'.
    La pérdida de datos (evaluaciones eliminadas) es aceptable en un rollback.
    """
    Assessment = apps.get_model('assessment', 'Assessment')
    Assessment.objects.update(content_copy=None)


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0003_assessment_content_copy"),
        ("contents", "0001_initial"), # Dependencia explícita para asegurar que ContentCopy está disponible
    ]

    operations = [
        migrations.RunPython(populate_content_copy_forward, populate_content_copy_backward),
    ]
