# Generated by Django 5.0.7 on 2025-10-26 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0004_populate_content_copy"),
        ("contents", "0003_alter_favoritefolder_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="content_copy",
            field=models.ForeignKey(
                default=1,
                help_text="La copia de estudio específica a la que está vinculada esta evaluación.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="contents.contentcopy",
                verbose_name="Copia de Estudio",
            ),
            preserve_default=False,
        ),
    ]
