# Generated by Django 5.0.7 on 2025-10-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0005_alter_assessment_content_copy"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_limit",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Número máximo de evaluaciones que un usuario puede generar en 24 horas.",
                        verbose_name="Límite Diario de Evaluaciones por Usuario",
                    ),
                ),
                (
                    "weekly_limit",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Número máximo de evaluaciones que un usuario puede generar en 7 días.",
                        verbose_name="Límite Semanal de Evaluaciones por Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Evaluaciones",
                "verbose_name_plural": "Configuraciones de Evaluaciones",
            },
        ),
    ]
