# Generated by Django 5.0.7 on 2025-10-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0006_assessmentsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="expiration_date",
            field=models.DateTimeField(
                blank=True,
                help_text="La evaluación debe realizarse antes de esta fecha.",
                null=True,
                verbose_name="Fecha de Caducidad para Realizar",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="results_expiration_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Los resultados de la evaluación estarán disponibles hasta esta fecha.",
                null=True,
                verbose_name="Fecha de Caducidad de Resultados",
            ),
        ),
    ]
