# Generated by Django 5.0.7 on 2025-10-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0007_assessment_expiration_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentsettings",
            name="assessment_expiration_seconds",
            field=models.PositiveIntegerField(
                default=86400,
                help_text="Tiempo máximo que un usuario tiene para completar una evaluación desde que está disponible.",
                verbose_name="Tiempo para Realizar una Evaluación (segundos)",
            ),
        ),
        migrations.AddField(
            model_name="assessmentsettings",
            name="results_expiration_days",
            field=models.PositiveIntegerField(
                default=7,
                help_text="Número de días que los resultados de una evaluación permanecen visibles.",
                verbose_name="Tiempo de Visibilidad de Resultados (días)",
            ),
        ),
    ]
