# Generated by Django 5.0.7 on 2025-11-10 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessment",
            "0008_assessmentsettings_assessment_expiration_seconds_and_more",
        ),
        ("contents", "0016_populate_sub_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="content",
            field=models.ForeignKey(
                editable=False,
                help_text="Se rellena automáticamente desde la Copia de Estudio.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="contents.contentmaterial",
                verbose_name="Contenido Original",
            ),
        ),
    ]
