# Generated by Django 5.0.7 on 2025-11-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0009_alter_assessment_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="last_error",
            field=models.TextField(
                blank=True, null=True, verbose_name="Último Error Registrado"
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente de Generación"),
                    ("PROCESSING", "Procesando Generación"),
                    ("COMPLETED", "Lista para Realizar"),
                    ("EXPIRED_UNTAKEN", "Expirada (No Realizada)"),
                    ("CORRECTING", "Corrigiendo"),
                    ("RESULTS_AVAILABLE", "Resultados Disponibles"),
                    ("CORRECTION_EXPIRED", "Corrección Expirada"),
                    ("FAILED_RETRYABLE", "Fallo (Reintentando)"),
                    ("FAILED_FATAL", "Fallo Permanente"),
                    ("USER_CANCELLED", "Cancelada por el Usuario"),
                ],
                default="PENDING",
                max_length=30,
                verbose_name="Estado",
            ),
        ),
    ]
