# Generated by Django 5.0.7 on 2025-11-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0010_assessment_last_error_alter_assessment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente de Generación"),
                    ("PROCESSING", "Generando Cuestionario"),
                    ("COMPLETED", "Listo para Realizar"),
                    ("CORRECTING", "Corrigiendo"),
                    ("RESULTS_AVAILABLE", "Resultados Disponibles"),
                    ("EXPIRED_UNTAKEN", "Expirado (No Realizado)"),
                    ("CORRECTION_EXPIRED", "Corrección Expirada"),
                    (
                        "GENERATION_FAILED_RETRYABLE",
                        "Fallo de Generación (Reintentando)",
                    ),
                    (
                        "GENERATION_FAILED_QUOTA",
                        "Fallo de Generación (Límite de Cuota)",
                    ),
                    (
                        "GENERATION_FAILED_FATAL",
                        "Fallo de Generación (Permanente)",
                    ),
                    (
                        "CORRECTION_FAILED_RETRYABLE",
                        "Fallo de Corrección (Reintentando)",
                    ),
                    (
                        "CORRECTION_FAILED_FATAL",
                        "Fallo de Corrección (Permanente)",
                    ),
                    ("USER_CANCELLED", "Cancelado por el Usuario"),
                ],
                default="PENDING",
                max_length=50,
                verbose_name="Estado",
            ),
        ),
    ]
