# Generated by Django 5.0.7 on 2025-11-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0012_alter_assessment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentsettings",
            name="event_log",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Historial de Eventos del Motor"
            ),
        ),
        migrations.AddField(
            model_name="assessmentsettings",
            name="is_running",
            field=models.BooleanField(
                default=False,
                help_text="Si está activado, el sistema buscará y procesará tareas de evaluación pendientes.",
                verbose_name="Motor de Evaluaciones Activado",
            ),
        ),
        migrations.AddField(
            model_name="assessmentsettings",
            name="last_run_status",
            field=models.TextField(
                blank=True, verbose_name="Estado del Último Ciclo del Orquestador"
            ),
        ),
        migrations.AddField(
            model_name="assessmentsettings",
            name="last_run_timestamp",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Última Ejecución del Orquestador"
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente de Generación"),
                    ("PROCESSING", "Generando Cuestionario"),
                    ("COMPLETED", "Listo para Realizar"),
                    ("AWAITING_CORRECTION", "Pendiente de Corrección"),
                    ("CORRECTING", "Corrigiendo"),
                    ("RESULTS_AVAILABLE", "Resultados Disponibles"),
                    ("EXPIRED_UNTAKEN", "Expirado (No Realizado)"),
                    ("CORRECTION_EXPIRED", "Corrección Expirada"),
                    (
                        "GENERATION_FAILED_RETRYABLE",
                        "Fallo de Generación (Reintentable)",
                    ),
                    (
                        "CORRECTION_FAILED_RETRYABLE",
                        "Fallo de Corrección (Reintentable)",
                    ),
                    ("GENERATION_FAILED_QUOTA", "Fallo de Generación (Cuota API)"),
                    ("GENERATION_FAILED_FATAL", "Fallo Permanente de Generación"),
                    ("CORRECTION_FAILED_FATAL", "Fallo Permanente de Corrección"),
                    ("PAUSED", "Pausada por el Administrador"),
                    ("USER_CANCELLED", "Cancelado por el Usuario"),
                ],
                default="PENDING",
                max_length=50,
                verbose_name="Estado",
            ),
        ),
    ]
