# Generated by Django 5.0.7 on 2025-11-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0013_assessmentsettings_event_log_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="event_log",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Registro detallado de los cambios de estado y errores de esta evaluación.",
                verbose_name="Historial de Eventos",
            ),
        ),
    ]
