# Generated by Django 5.0.7 on 2025-12-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0014_assessment_event_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente de Generación"),
                    ("PROCESSING", "Generando Cuestionario"),
                    ("COMPLETED", "Listo para Realizar"),
                    ("AWAITING_CORRECTION", "Pendiente de Corrección"),
                    ("CORRECTING", "Corrigiendo"),
                    ("RESULTS_AVAILABLE", "Resultados Disponibles"),
                    ("EXPIRED_UNTAKEN", "Expirado (No Realizado)"),
                    ("CORRECTION_EXPIRED", "Corrección Expirada"),
                    (
                        "GENERATION_FAILED_RETRYABLE",
                        "Fallo de Generación (Reintentable)",
                    ),
                    (
                        "CORRECTION_FAILED_RETRYABLE",
                        "Fallo de Corrección (Reintentable)",
                    ),
                    ("GENERATION_FAILED_QUOTA", "Fallo de Generación (Cuota API)"),
                    ("GENERATION_FAILED_FATAL", "Fallo Permanente de Generación"),
                    ("CORRECTION_FAILED_FATAL", "Fallo Permanente de Corrección"),
                    ("PAUSED", "Pausada por el Administrador"),
                    ("CANCELLED", "Cancelada por Administrador"),
                    ("USER_CANCELLED", "Cancelado por el Usuario"),
                ],
                default="PENDING",
                max_length=50,
                verbose_name="Estado",
            ),
        ),
    ]
