# Generated by Django 5.0.7 on 2026-01-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0015_alter_assessment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="target_segment",
            field=models.CharField(
                choices=[
                    ("GLOBAL", "Evaluación Global (Todo el temario)"),
                    ("Q1", "Primer Trimestre (Inicio - 33%)"),
                    ("Q2", "Segundo Trimestre (Medio - 33%-66%)"),
                    ("Q3", "Tercer Trimestre (Final - 66%-100%)"),
                ],
                default="GLOBAL",
                help_text="⚠️ AVISO: La división por trimestres es una estimación basada en la longitud del texto y podría no coincidir exactamente con los cortes de la guía docente oficial.",
                max_length=10,
                verbose_name="Segmento del Temario",
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="audio_file",
            field=models.FileField(
                blank=True,
                help_text="Grabación de voz del usuario para ejercicios de Speaking.",
                null=True,
                upload_to="assessment/audio/%Y/%m/",
                verbose_name="Audio (Speaking)",
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="score_grammar",
            field=models.FloatField(
                blank=True,
                help_text="Calificación específica sobre la calidad del lenguaje (para Writing/Speaking), separada del contenido.",
                null=True,
                verbose_name="Puntuación Gramatical/Estilo",
            ),
        ),
    ]
