# Generated by Django 5.0.7 on 2026-01-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0016_assessment_target_segment_useranswer_audio_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="options",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de opciones para preguntas tipo test (JSON). Ej: ['A) ...', 'B) ...']",
                verbose_name="Opciones de Respuesta",
            ),
        ),
    ]
