# Generated by Django 5.0.7 on 2026-01-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0017_question_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessment",
            name="target_segment",
        ),
        migrations.AddField(
            model_name="assessment",
            name="listening_transcript",
            field=models.TextField(
                blank=True,
                help_text="Guion generado por IA para la parte de comprensión auditiva.",
                null=True,
                verbose_name="Transcripción de Audio (Listening)",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="reading_stimulus",
            field=models.TextField(
                blank=True,
                help_text="Texto generado por IA que sirve de base para la evaluación.",
                null=True,
                verbose_name="Estímulo de Lectura (Reading)",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="selection_range",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Almacena los índices o slugs de los temas del master_schema seleccionados.",
                null=True,
                verbose_name="Rango de Selección (JSON)",
            ),
        ),
    ]
