# Generated by Django 5.0.7 on 2026-01-17 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0018_remove_assessment_target_segment_and_more"),
        (
            "contents",
            "0019_userstudynavigation_alter_discipline_unique_together_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessmentsettings",
            options={
                "verbose_name": "Configuración",
                "verbose_name_plural": "Configuraciones",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["id"],
                "verbose_name": "Pregunta",
                "verbose_name_plural": "Preguntas",
            },
        ),
        migrations.AlterModelOptions(
            name="useranswer",
            options={
                "verbose_name": "Respuesta del Usuario",
                "verbose_name_plural": "Respuestas del Usuario",
            },
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="listening_transcript",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="reading_stimulus",
        ),
        migrations.RemoveField(
            model_name="assessmentsettings",
            name="last_run_status",
        ),
        migrations.RemoveField(
            model_name="assessmentsettings",
            name="last_run_timestamp",
        ),
        migrations.RemoveField(
            model_name="question",
            name="question_type",
        ),
        migrations.RemoveField(
            model_name="useranswer",
            name="audio_file",
        ),
        migrations.RemoveField(
            model_name="useranswer",
            name="correction_expiration_date",
        ),
        migrations.RemoveField(
            model_name="useranswer",
            name="score_grammar",
        ),
        migrations.AddField(
            model_name="assessment",
            name="archetype",
            field=models.CharField(
                choices=[
                    ("SCIENCES", "Ciencias Exactas"),
                    ("LANGUAGES", "Idiomas"),
                    ("HUMANITIES", "Humanidades"),
                ],
                db_index=True,
                default="HUMANITIES",
                max_length=20,
                verbose_name="Arquetipo",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="prompt_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Contenedor para textos base, scripts de audio o fórmulas.",
                verbose_name="Datos del Profesor (JSON)",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="widget_type",
            field=models.CharField(
                choices=[
                    ("TEXT_AREA", "Área de Texto (Desarrollo/Problema)"),
                    ("AUDIO_RECORDER", "Grabadora de Voz (Speaking)"),
                    ("RADIO_SELECT", "Opción Múltiple (Test)"),
                    ("MATH_INPUT", "Editor Matemático (LaTeX)"),
                ],
                default="TEXT_AREA",
                max_length=20,
                verbose_name="Widget de UI",
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="assessment/attachments/%Y/%m/",
                verbose_name="Archivo Adjunto (Audio/Imagen)",
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="content",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="contents.contentmaterial",
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="content_copy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="contents.contentcopy",
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="event_log",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="expiration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="last_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="questions_processed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="results_expiration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="selection_range",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente de Generación"),
                    ("PROCESSING", "Generando Cuestionario"),
                    ("COMPLETED", "Listo para Realizar"),
                    ("AWAITING_CORRECTION", "Pendiente de Corrección"),
                    ("CORRECTING", "Corrigiendo"),
                    ("RESULTS_AVAILABLE", "Resultados Disponibles"),
                    ("EXPIRED_UNTAKEN", "Expirado (No Realizado)"),
                    ("CORRECTION_EXPIRED", "Corrección Expirada"),
                    ("GENERATION_FAILED_RETRYABLE", "Fallo Reintentable"),
                    ("GENERATION_FAILED_FATAL", "Fallo Permanente"),
                    ("USER_CANCELLED", "Cancelado por el Usuario"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="total_questions_expected",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="was_viewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="assessmentsettings",
            name="assessment_expiration_seconds",
            field=models.PositiveIntegerField(default=86400),
        ),
        migrations.AlterField(
            model_name="assessmentsettings",
            name="daily_limit",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="assessmentsettings",
            name="event_log",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="assessmentsettings",
            name="is_running",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="assessmentsettings",
            name="results_expiration_days",
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name="assessmentsettings",
            name="weekly_limit",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="question",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="assessment.assessment",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="model_answer",
            field=models.TextField(verbose_name="Respuesta Modelo"),
        ),
        migrations.AlterField(
            model_name="question",
            name="options",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Opciones (JSON)"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.TextField(verbose_name="Enunciado"),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="answer_text",
            field=models.TextField(verbose_name="Respuesta del Usuario (Texto/LaTeX)"),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="answered_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_answers",
                to="assessment.question",
            ),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
