# Generated by Django 5.0.7 on 2026-01-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0019_alter_assessmentsettings_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="archetype",
            field=models.CharField(
                choices=[
                    ("SCIENCES", "Ciencias Exactas"),
                    ("LANGUAGES", "Idiomas"),
                    ("HUMANITIES", "Humanidades"),
                ],
                db_index=True,
                default="HUMANITIES",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="prompt_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente de Generación"),
                    ("PROCESSING", "Generando Cuestionario"),
                    ("COMPLETED", "Listo para Realizar"),
                    ("AWAITING_CORRECTION", "Pendiente de Corrección"),
                    ("CORRECTING", "Corrigiendo"),
                    ("RESULTS_AVAILABLE", "Resultados Disponibles"),
                    ("EXPIRED_UNTAKEN", "Expirado (No Realizado)"),
                    ("CORRECTION_EXPIRED", "Corrección Expirada"),
                    ("GENERATION_FAILED_RETRYABLE", "Fallo Reintentable"),
                    ("GENERATION_FAILED_FATAL", "Fallo Permanente"),
                    ("CANCELLED", "Cancelada por Administrador"),
                    ("USER_CANCELLED", "Cancelado por el Usuario"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="model_answer",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="question",
            name="options",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="question",
            name="widget_type",
            field=models.CharField(
                choices=[
                    ("TEXT_AREA", "Área de Texto"),
                    ("AUDIO_RECORDER", "Grabadora de Voz"),
                    ("RADIO_SELECT", "Opción Múltiple"),
                    ("MATH_INPUT", "Editor Matemático"),
                ],
                default="TEXT_AREA",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="answer_text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="assessment/attachments/%Y/%m/"
            ),
        ),
    ]
