# Generated by Django 5.0.7 on 2026-01-17 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0020_alter_assessment_archetype_and_more"),
        (
            "contents",
            "0019_userstudynavigation_alter_discipline_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessment",
            options={},
        ),
        migrations.AlterModelOptions(
            name="assessmentsettings",
            options={},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={},
        ),
        migrations.AlterModelOptions(
            name="useranswer",
            options={},
        ),
        migrations.AddField(
            model_name="assessment",
            name="listening_transcript",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="reading_stimulus",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessmentsettings",
            name="last_run_status",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assessmentsettings",
            name="last_run_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("open_ended", "Respuesta Abierta"),
                    ("multiple_choice", "Opción Múltiple"),
                ],
                default="open_ended",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="correction_expiration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="content",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="contents.contentmaterial",
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente de Generación"),
                    ("PROCESSING", "Generando Cuestionario"),
                    ("COMPLETED", "Listo para Realizar"),
                    ("AWAITING_CORRECTION", "Pendiente de Corrección"),
                    ("CORRECTING", "Corrigiendo"),
                    ("RESULTS_AVAILABLE", "Resultados Disponibles"),
                    ("EXPIRED_UNTAKEN", "Expirado (No Realizado)"),
                    ("CORRECTION_EXPIRED", "Corrección Expirada"),
                    (
                        "GENERATION_FAILED_RETRYABLE",
                        "Fallo de Generación (Reintentable)",
                    ),
                    (
                        "CORRECTION_FAILED_RETRYABLE",
                        "Fallo de Corrección (Reintentable)",
                    ),
                    ("GENERATION_FAILED_QUOTA", "Fallo de Generación (Cuota API)"),
                    ("GENERATION_FAILED_FATAL", "Fallo Permanente de Generación"),
                    ("CORRECTION_FAILED_FATAL", "Fallo Permanente de Corrección"),
                    ("PAUSED", "Pausada por el Administrador"),
                    ("CANCELLED", "Cancelada por Administrador"),
                    ("USER_CANCELLED", "Cancelado por el Usuario"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
