# Generated by Django 5.0.7 on 2026-01-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0021_alter_assessment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Evaluación",
                "verbose_name_plural": "1. Listado de Evaluaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="assessmentsettings",
            options={
                "verbose_name": "Ajuste de Motor",
                "verbose_name_plural": "0. Configuración del Motor",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["id"],
                "verbose_name": "Pregunta",
                "verbose_name_plural": "2. Banco de Preguntas",
            },
        ),
        migrations.AlterModelOptions(
            name="useranswer",
            options={
                "verbose_name": "Respuesta de Alumno",
                "verbose_name_plural": "3. Respuestas Recibidas",
            },
        ),
        migrations.AddField(
            model_name="assessment",
            name="rejected_archetypes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de arquetipos rechazados explícitamente por el usuario",
            ),
        ),
    ]
