# Generated by Django 5.0.7 on 2026-01-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0022_alter_assessment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="generated_audio",
            field=models.FileField(
                blank=True,
                help_text="Audio nativo generado por Gemini 2.5",
                null=True,
                upload_to="assessment/generated_audio/%Y/%m/",
            ),
        ),
    ]
