# Generated by Django 5.0.7 on 2026-01-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0023_assessment_generated_audio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="archetype",
            field=models.CharField(
                choices=[
                    ("EXACT_SCIENCES", "Ciencias Exactas"),
                    ("HEALTH_SCIENCES", "Ciencias de la Salud"),
                    ("LEGAL", "Derecho y Sociales"),
                    ("LANGUAGES", "Idiomas"),
                    ("ARTS", "Arte y Humanidades"),
                    ("SOCIETY", "Sociedad y Pensamiento"),
                    ("HISTORY", "Historia y Geografía"),
                    ("PHILOLOGY", "Filología y Lingüística"),
                    ("HUMANITIES_GENERIC", "Humanidades (Genérico)"),
                ],
                db_index=True,
                default="HUMANITIES_GENERIC",
                max_length=20,
            ),
        ),
    ]
