# Generated by Django 5.0.7 on 2026-01-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0024_alter_assessment_archetype"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessment",
            options={
                "verbose_name": "Evaluación",
                "verbose_name_plural": "Evaluaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="assessmentsettings",
            options={},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={},
        ),
        migrations.AlterModelOptions(
            name="useranswer",
            options={},
        ),
        migrations.RemoveField(
            model_name="assessmentsettings",
            name="daily_limit",
        ),
        migrations.RemoveField(
            model_name="assessmentsettings",
            name="last_run_status",
        ),
        migrations.RemoveField(
            model_name="assessmentsettings",
            name="last_run_timestamp",
        ),
        migrations.RemoveField(
            model_name="assessmentsettings",
            name="weekly_limit",
        ),
        migrations.AlterField(
            model_name="assessment",
            name="archetype",
            field=models.CharField(
                choices=[
                    ("LOGIC_AND_TECH", "LOGIC & TECH (Ingeniería y Ciencias)"),
                    ("CEFR_LANGUAGES", "CEFR LANGUAGES (Idiomas)"),
                    ("SOCIO_LEGAL", "SOCIO LEGAL (Derecho y Sociales)"),
                    ("HEALTH_SCIENCES", "HEALTH SCIENCES (Salud)"),
                    ("HUMANITIES_ARTS", "HUMANITIES & ARTS (Arte y Letras)"),
                ],
                db_index=True,
                default="HUMANITIES_ARTS",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="generated_audio",
            field=models.FileField(
                blank=True, null=True, upload_to="assessment/generated_audio/%Y/%m/"
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="rejected_archetypes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="question",
            name="widget_type",
            field=models.CharField(
                choices=[
                    ("TEXT_AREA", "Área de Texto"),
                    ("AUDIO_RECORDER", "Grabadora de Voz"),
                    ("RADIO_SELECT", "Opción Múltiple"),
                ],
                default="TEXT_AREA",
                max_length=20,
            ),
        ),
    ]
