# Generated by Django 5.0.7 on 2026-01-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0025_alter_assessment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Evaluación",
                "verbose_name_plural": "1. Listado de Evaluaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="assessmentsettings",
            options={
                "verbose_name": "Ajuste de Motor",
                "verbose_name_plural": "0. Configuración del Motor",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["id"],
                "verbose_name": "Pregunta",
                "verbose_name_plural": "2. Banco de Preguntas",
            },
        ),
        migrations.AlterModelOptions(
            name="useranswer",
            options={
                "verbose_name": "Respuesta de Alumno",
                "verbose_name_plural": "3. Respuestas Recibidas",
            },
        ),
        migrations.AddField(
            model_name="assessmentsettings",
            name="daily_limit",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="assessmentsettings",
            name="last_run_status",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assessmentsettings",
            name="last_run_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessmentsettings",
            name="weekly_limit",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="archetype",
            field=models.CharField(
                choices=[
                    ("LOGIC_AND_TECH", "LOGIC & TECH (Ingeniería y Ciencias)"),
                    ("CEFR_LANGUAGES", "CEFR LANGUAGES (Idiomas)"),
                    ("SOCIO_LEGAL", "SOCIO LEGAL (Derecho y Sociales)"),
                    ("HEALTH_SCIENCES", "HEALTH SCIENCES (Salud)"),
                    ("HUMANITIES_ARTS", "HUMANITIES & ARTS (Arte y Letras)"),
                ],
                db_index=True,
                default="HUMANITIES_ARTS",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="generated_audio",
            field=models.FileField(
                blank=True,
                help_text="Audio nativo generado por Gemini 2.5",
                null=True,
                upload_to="assessment/generated_audio/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="rejected_archetypes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de arquetipos rechazados explícitamente por el usuario",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="widget_type",
            field=models.CharField(
                choices=[
                    ("TEXT_AREA", "Área de Texto"),
                    ("AUDIO_RECORDER", "Grabadora de Voz"),
                    ("RADIO_SELECT", "Opción Múltiple"),
                    ("MATH_INPUT", "Editor Matemático"),
                ],
                default="TEXT_AREA",
                max_length=20,
            ),
        ),
    ]
