# Generated by Django 5.0.7 on 2026-01-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0026_alter_assessment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="section_label",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Cabecera de Sección",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="widget_type",
            field=models.CharField(
                choices=[
                    ("TEXT_AREA", "Área de Texto"),
                    ("AUDIO_RECORDER", "Grabadora de Voz"),
                    ("RADIO_SELECT", "Opción Múltiple"),
                    ("MATH_INPUT", "Editor Matemático"),
                    ("FILE_UPLOAD", "Subida de Archivo/Foto"),
                ],
                default="TEXT_AREA",
                max_length=20,
            ),
        ),
    ]
