# Generated by Django 5.0.7 on 2026-01-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0027_question_section_label_alter_question_widget_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["id"],
                "verbose_name": "Pregunta (Emulador UGR)",
                "verbose_name_plural": "2. Banco de Preguntas",
            },
        ),
        migrations.RemoveField(
            model_name="question",
            name="question_type",
        ),
        migrations.RemoveField(
            model_name="question",
            name="widget_type",
        ),
        migrations.AddField(
            model_name="question",
            name="interaction_type",
            field=models.CharField(
                choices=[
                    ("QT_SEL", "Selección Simple (Test)"),
                    ("QT_MATCH", "Emparejamiento"),
                    ("QT_CLZ_OPT", "Cloze con Opciones"),
                    ("QT_CLZ_OPN", "Cloze Abierto"),
                    ("QT_TRF", "Transformación (Re-writing)"),
                    ("QT_PROD", "Producción Libre"),
                ],
                default="QT_PROD",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="response_mode",
            field=models.CharField(
                choices=[
                    ("REQ_RADIO", "Radio Buttons"),
                    ("REQ_DROP", "Desplegables inline"),
                    ("REQ_INPUT", "Caja de texto inline"),
                    ("REQ_DUAL", "Escritura Dual (Texto + Archivo)"),
                    ("REQ_REC", "Grabadora Multimedia"),
                ],
                default="REQ_DUAL",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("SRC_DIR", "Directo (Sin estímulo)"),
                    ("SRC_TXT", "Texto / Reading"),
                    ("SRC_AUD", "Audio MP3 / Listening"),
                    ("SRC_IMG", "Imagen / Fotografía"),
                    ("SRC_HYB", "Híbrido (Texto + Audio)"),
                ],
                default="SRC_DIR",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="options",
            field=models.JSONField(
                blank=True, default=list, help_text="Opciones para Test o Cloze"
            ),
        ),
    ]
