# Generated by Django 5.0.7 on 2026-01-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessment",
            "0028_alter_question_options_remove_question_question_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="interaction_type",
            field=models.CharField(
                choices=[
                    ("QT_SEL", "Selección Simple (Test)"),
                    ("QT_MATCH", "Emparejamiento"),
                    ("QT_CLZ_OPT", "Cloze con Opciones"),
                    ("QT_CLZ_OPN", "Cloze Abierto"),
                    ("QT_TRF", "Transformación (Re-writing)"),
                    ("QT_PROD", "Producción Libre"),
                    ("QT_ORDER", "Ordenación"),
                ],
                default="QT_PROD",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="response_mode",
            field=models.CharField(
                choices=[
                    ("REQ_RADIO", "Radio Buttons"),
                    ("REQ_DROP", "Desplegables inline"),
                    ("REQ_INPUT", "Caja de texto inline"),
                    ("REQ_DUAL", "Escritura Dual (Texto + Archivo)"),
                    ("REQ_REC", "Grabadora Multimedia"),
                    ("REQ_MATCH", "Matriz de Emparejamiento"),
                    ("REQ_ORDER", "Lista de Ordenación"),
                ],
                default="REQ_DUAL",
                max_length=10,
            ),
        ),
    ]
