# Generated by Django 5.0.7 on 2026-01-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0029_alter_question_interaction_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="interaction_type",
            field=models.CharField(
                choices=[
                    ("QT_SEL", "Selección Simple (Test)"),
                    ("QT_MATCH", "Emparejamiento"),
                    ("QT_CLZ_OPT", "Cloze con Opciones"),
                    ("QT_CLZ_OPN", "Cloze Abierto"),
                    ("QT_TRF", "Transformación (Re-writing)"),
                    ("QT_PROD", "Producción Libre"),
                    ("QT_ORDER", "Ordenación"),
                ],
                default="QT_PROD",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="response_mode",
            field=models.CharField(
                choices=[
                    ("REQ_RADIO", "Radio Buttons"),
                    ("REQ_DROP", "Desplegables inline"),
                    ("REQ_INPUT", "Caja de texto inline"),
                    ("REQ_DUAL", "Escritura Dual (Texto + Archivo)"),
                    ("REQ_REC", "Grabadora Multimedia"),
                    ("REQ_MATCH", "Matriz de Emparejamiento"),
                    ("REQ_ORDER", "Lista de Ordenación"),
                ],
                default="REQ_DUAL",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("SRC_DIR", "Directo (Sin estímulo)"),
                    ("SRC_TXT", "Texto / Reading"),
                    ("SRC_AUD", "Audio MP3 / Listening"),
                    ("SRC_IMG", "Imagen / Fotografía"),
                    ("SRC_HYB", "Híbrido (Texto + Audio)"),
                ],
                default="SRC_DIR",
                max_length=50,
            ),
        ),
    ]
