# Generated by Django 5.0.7 on 2026-01-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0030_alter_question_interaction_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="language_itinerary",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MAIOR", "Maior (Especialidad / C1)"),
                    ("MINOR", "Minor (Segunda Lengua / A1-B2)"),
                ],
                max_length=10,
                null=True,
                verbose_name="Itinerario Lingüístico",
            ),
        ),
    ]
