# Generated by Django 5.0.7 on 2026-01-13 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_lang",
                    models.CharField(max_length=100, verbose_name="Idioma Origen"),
                ),
                (
                    "target_lang",
                    models.CharField(max_length=100, verbose_name="Idioma Destino"),
                ),
                (
                    "char_count",
                    models.IntegerField(
                        help_text="Longitud del texto original",
                        verbose_name="Caracteres",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "is_successful",
                    models.BooleanField(default=True, verbose_name="Éxito"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Técnico"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Traducción",
                "verbose_name_plural": "Registros de Traducción",
                "ordering": ["-timestamp"],
            },
        ),
    ]
