# Generated by Django 5.0.7 on 2025-11-26 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "contents",
            "0019_userstudynavigation_alter_discipline_unique_together_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("content_error", "Error en Contenido"),
                            ("suggestion", "Sugerencia de Mejora"),
                            ("technical", "Problema Técnico"),
                        ],
                        default="suggestion",
                        max_length=20,
                        verbose_name="Tipo de Reporte",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("in_progress", "En Progreso"),
                            ("resolved", "Resuelto"),
                            ("rejected", "Descartado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Asunto")),
                ("description", models.TextField(verbose_name="Descripción detallada")),
                (
                    "admin_response",
                    models.TextField(
                        blank=True, verbose_name="Respuesta del Administrador"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "content_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="contents.contentmaterial",
                        verbose_name="Contenido Relacionado",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte de Feedback",
                "verbose_name_plural": "Reportes de Feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
