from .legal_strategy import generate_legal_prompt
from .languages_strategy import generate_languages_stimuli_prompt, generate_languages_item_prompt
from .humanities_strategy import generate_humanities_prompt
from .sciences_strategy import generate_sciences_prompt
from .health_strategy import generate_health_prompt
from .classifier import generate_classifier_prompt
