# Generated by Django 5.0.7 on 2025-10-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_username_display",
                    models.CharField(
                        max_length=150,
                        verbose_name="Nombre de Usuario del Remitente (para mostrar)",
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenido del Mensaje")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Marca de Tiempo"
                    ),
                ),
                (
                    "is_deleted_by_moderator",
                    models.BooleanField(
                        default=False,
                        help_text="Checked if the message was deleted by a moderator or creator.",
                        verbose_name="¿Borrado por Moderador?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de Chat",
                "verbose_name_plural": "Mensajes de Chat",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nombre de la Sala"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Automatically generated from the name if left empty.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "is_private",
                    models.BooleanField(default=False, verbose_name="¿Es Privada?"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "is_platform_default",
                    models.BooleanField(
                        default=False,
                        verbose_name="¿Es Sala por Defecto de la Plataforma?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sala de Chat",
                "verbose_name_plural": "Salas de Chat",
                "ordering": ["-is_platform_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="RoomMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Unión"
                    ),
                ),
                (
                    "is_silenced",
                    models.BooleanField(
                        default=False, verbose_name="¿Está Silenciado?"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Pending Approval"),
                            ("member", "Member"),
                            ("rejected", "Rejected"),
                            ("invited", "Invited"),
                        ],
                        default="member",
                        max_length=20,
                        verbose_name="Estado de Membresía",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("member", "Member"), ("moderator", "Moderator")],
                        default="member",
                        max_length=10,
                        verbose_name="Rol en la Sala",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membresía de Sala",
                "verbose_name_plural": "Membresías de Sala",
                "ordering": ["room", "date_joined"],
            },
        ),
    ]
