# Generated by Django 5.0.7 on 2025-10-08 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_chat_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Remitente (Usuario)",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_chat_rooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creador",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.chatroom",
                verbose_name="Sala",
            ),
        ),
        migrations.AddField(
            model_name="roommembership",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="chat.chatroom",
                verbose_name="Sala",
            ),
        ),
        migrations.AddField(
            model_name="roommembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roommembership",
            unique_together={("user", "room")},
        ),
    ]
