# Generated by Django 5.0.7 on 2025-11-24 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academic_structure",
            "0006_remove_subject_content_hash_contenthashfamily_and_more",
        ),
        ("chat", "0002_initial"),
        (
            "contents",
            "0019_userstudynavigation_alter_discipline_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="target_master_category",
            field=models.OneToOneField(
                blank=True,
                help_text="Si esta sala pertenece a una categoría maestra de contenido libre.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_room",
                to="contents.freecontentmastercategory",
                verbose_name="Categoría Maestra Vinculada",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="target_sub_category",
            field=models.OneToOneField(
                blank=True,
                help_text="Si esta sala pertenece a una subcategoría de contenido libre.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_room",
                to="contents.freecontentsubcategory",
                verbose_name="Subcategoría Vinculada",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="target_subject",
            field=models.OneToOneField(
                blank=True,
                help_text="Si esta sala pertenece a una asignatura académica.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_room",
                to="academic_structure.subject",
                verbose_name="Asignatura Vinculada",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="is_private",
            field=models.BooleanField(default=True, verbose_name="¿Es Privada?"),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Automatically generated from the name or context if left empty.",
                max_length=255,
                unique=True,
            ),
        ),
    ]
