# Generated by Django 5.0.7 on 2026-03-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatroom_target_master_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="sender_username_display",
            field=models.CharField(
                db_index=True,
                max_length=150,
                verbose_name="Nombre de Usuario del Remitente (para mostrar)",
            ),
        ),
    ]
