# Generated by Django 5.0.7 on 2025-12-24 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "academic_structure",
            "0007_alter_university_options_alter_branch_university_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("start_time", models.DateTimeField(verbose_name="Fecha de inicio")),
                ("end_time", models.DateTimeField(verbose_name="Fecha de fin")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CL", "Clase"),
                            ("EX", "Examen"),
                            ("PR", "Práctica"),
                            ("TU", "Tutoría"),
                            ("ST", "Sesión de Estudio"),
                            ("DL", "Entrega / Deadline"),
                            ("PE", "Personal / Otro"),
                        ],
                        default="PE",
                        max_length=2,
                        verbose_name="Tipo de evento",
                    ),
                ),
                (
                    "is_all_day",
                    models.BooleanField(default=False, verbose_name="Todo el día"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ubicación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="academic_events",
                        to="academic_structure.subject",
                        verbose_name="Asignatura",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento Académico",
                "verbose_name_plural": "Eventos Académicos",
                "ordering": ["start_time"],
            },
        ),
    ]
