# Generated by Django 5.0.7 on 2025-12-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicevent",
            name="reminder_sent",
            field=models.BooleanField(
                default=False, verbose_name="Recordatorio enviado"
            ),
        ),
    ]
