# Generated by Django 5.0.7 on 2025-12-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_academicevent_reminder_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicevent",
            name="subject_name_display",
            field=models.CharField(
                blank=True,
                help_text="Nombre manual si no es una asignatura oficial.",
                max_length=200,
                verbose_name="Nombre de Asignatura / Curso",
            ),
        ),
    ]
