# Generated by Django 5.0.7 on 2025-10-08 18:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nombre de Rama"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default="",
                        help_text="Unique identifier for URLs.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "has_public_content",
                    models.BooleanField(
                        default=False,
                        help_text="Se actualiza automáticamente. Indica si alguna asignatura descendiente tiene material público.",
                        verbose_name="Tiene Contenido Público",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rama de Conocimiento",
                "verbose_name_plural": "Ramas de Conocimiento",
                "ordering": ["university__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Código de Universidad"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de Universidad"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="URL del Portal de Estudios",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default="",
                        help_text="Unique identifier for URLs.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "has_public_content",
                    models.BooleanField(
                        default=False,
                        help_text="Se actualiza automáticamente. Indica si alguna asignatura descendiente tiene material público.",
                        verbose_name="Tiene Contenido Público",
                    ),
                ),
            ],
            options={
                "verbose_name": "Universidad",
                "verbose_name_plural": "Universidades",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Degree",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, verbose_name="Código de Titulación"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de Titulación"
                    ),
                ),
                (
                    "degree_type",
                    models.CharField(
                        choices=[
                            ("GR", "Grado"),
                            ("MA", "Máster"),
                            ("DO", "Doctorado"),
                            ("OT", "Otro"),
                        ],
                        default="GR",
                        max_length=2,
                        verbose_name="Tipo de Titulación",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="URL de la Titulación",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default="",
                        help_text="Unique identifier for URLs.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "has_public_content",
                    models.BooleanField(
                        default=False,
                        help_text="Se actualiza automáticamente. Indica si alguna asignatura descendiente tiene material público.",
                        verbose_name="Tiene Contenido Público",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="degrees",
                        to="academic_structure.branch",
                        verbose_name="Rama de Conocimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Titulación",
                "verbose_name_plural": "Titulaciones",
                "ordering": ["branch__name", "name"],
                "unique_together": {("branch", "name")},
            },
        ),
        migrations.AddField(
            model_name="branch",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="academic_structure.university",
                verbose_name="Universidad",
            ),
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de Asignatura"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default="",
                        help_text="Unique identifier for URLs.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("TR", "Troncal"),
                            ("OB", "Obligatoria"),
                            ("OP", "Optativa"),
                            ("BA", "Formación Básica"),
                            ("OT", "Otra"),
                        ],
                        max_length=3,
                        verbose_name="Tipo de Asignatura",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(verbose_name="Año Académico"),
                ),
                (
                    "semester",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Semestre"
                    ),
                ),
                (
                    "has_public_content",
                    models.BooleanField(
                        default=False,
                        help_text="Se actualiza automáticamente. Indica si esta asignatura tiene material público.",
                        verbose_name="Tiene Contenido Público",
                    ),
                ),
                (
                    "learning_objectives",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de objetivos de aprendizaje extraídos de la guía docente.",
                        null=True,
                        verbose_name="Objetivos de Aprendizaje",
                    ),
                ),
                (
                    "course_content_outline",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista unificada del temario teórico y práctico.",
                        null=True,
                        verbose_name="Esquema de Contenidos",
                    ),
                ),
                (
                    "bibliography",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Diccionario con bibliografía fundamental y complementaria.",
                        null=True,
                        verbose_name="Bibliografía",
                    ),
                ),
                (
                    "degree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="academic_structure.degree",
                        verbose_name="Titulación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignatura",
                "verbose_name_plural": "Asignaturas",
                "ordering": [
                    "degree__branch__university__name",
                    "degree__branch__name",
                    "degree__name",
                    "year",
                    "semester",
                    "name",
                ],
                "unique_together": {("degree", "name", "year", "semester")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="branch",
            unique_together={("university", "name")},
        ),
    ]
