# Generated by Django 5.0.7 on 2025-10-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="content_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 hash del contenido canónico para detectar duplicados.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
