# Generated by Django 5.0.7 on 2025-10-25 19:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0002_subject_content_hash"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="subject",
            name="degree",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="academic_structure.degree",
                verbose_name="Titulación (Antiguo)",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="year",
            field=models.PositiveSmallIntegerField(
                verbose_name="Año Académico (Antiguo)"
            ),
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="Año")),
                (
                    "has_public_content",
                    models.BooleanField(
                        default=False,
                        help_text="Se actualiza automáticamente. Indica si alguna asignatura de este año tiene material público.",
                        verbose_name="Tiene Contenido Público",
                    ),
                ),
                (
                    "degree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_years",
                        to="academic_structure.degree",
                        verbose_name="Titulación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Año Académico",
                "verbose_name_plural": "Años Académicos",
                "ordering": ["degree__name", "year"],
                "unique_together": {("degree", "year")},
            },
        ),
        migrations.AddField(
            model_name="subject",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subjects",
                to="academic_structure.academicyear",
                verbose_name="Año Académico",
            ),
        ),
    ]
