# Generated by Django 5.0.7 on 2025-10-25 21:12

from django.db import migrations

def migrate_subject_to_academic_year(apps, schema_editor):
    """
    Data migration to populate the new academic_year field in the Subject model.
    It iterates over all existing Subjects, finds or creates the corresponding
    AcademicYear based on the old 'degree' and 'year' fields, and links it.
    """
    Subject = apps.get_model('academic_structure', 'Subject')
    AcademicYear = apps.get_model('academic_structure', 'AcademicYear')
    
    for subject in Subject.objects.all():
        # Using get_or_create ensures that we don't create duplicate AcademicYear objects
        # for subjects that share the same degree and year.
        academic_year, created = AcademicYear.objects.get_or_create(
            degree=subject.degree,
            year=subject.year
        )
        
        # Link the found or newly created AcademicYear to the subject.
        subject.academic_year = academic_year
        subject.save(update_fields=['academic_year'])

def reverse_migration(apps, schema_editor):
    """
    Reverses the data migration by setting the academic_year field to null.
    The actual data relationship is not lost as it's still in the old 'degree'
    and 'year' fields at this migration state.
    """
    Subject = apps.get_model('academic_structure', 'Subject')
    Subject.objects.update(academic_year=None)


class Migration(migrations.Migration):

    dependencies = [
        ('academic_structure', '0003_alter_subject_unique_together_alter_subject_degree_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_subject_to_academic_year, reverse_code=reverse_migration),
    ]
