# Generated by Django 5.0.7 on 2025-10-25 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0004_auto_20251025_2112"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={
                "ordering": [
                    "academic_year__degree__branch__university__name",
                    "academic_year__degree__branch__name",
                    "academic_year__degree__name",
                    "academic_year__year",
                    "semester",
                    "name",
                ],
                "verbose_name": "Asignatura",
                "verbose_name_plural": "Asignaturas",
            },
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("academic_year", "name", "semester")},
        ),
        migrations.AlterField(
            model_name="subject",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="academic_structure.academicyear",
                verbose_name="Año Académico",
            ),
        ),
        migrations.RemoveField(
            model_name="subject",
            name="degree",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="year",
        ),
    ]
