# Generated by Django 5.0.7 on 2025-11-04 22:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academic_structure",
            "0005_alter_subject_options_alter_subject_unique_together_and_more",
        ),
        ("contents", "0006_update_public_status_by_rules"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="content_hash",
        ),
        migrations.CreateModel(
            name="ContentHashFamily",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash del contenido canónico que define a esta familia.",
                        max_length=64,
                        unique=True,
                        verbose_name="Hash de Contenido",
                    ),
                ),
                (
                    "content_material",
                    models.OneToOneField(
                        blank=True,
                        help_text="El único material de contenido generado para esta familia.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_hash_family",
                        to="contents.contentmaterial",
                        verbose_name="Material de Contenido Asociado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Familia de Contenido",
                "verbose_name_plural": "Familias de Contenido",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="subject",
            name="content_hash_family",
            field=models.ForeignKey(
                blank=True,
                help_text="Vincula esta asignatura a una familia de contenido idéntico.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subjects",
                to="academic_structure.contenthashfamily",
                verbose_name="Familia de Contenido",
            ),
        ),
    ]
