# Generated by Django 5.0.7 on 2025-11-27 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academic_structure",
            "0006_remove_subject_content_hash_contenthashfamily_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="university",
            options={
                "ordering": ["name"],
                "verbose_name": "Institución",
                "verbose_name_plural": "Instituciones",
            },
        ),
        migrations.AlterField(
            model_name="branch",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="academic_structure.university",
                verbose_name="Institución",
            ),
        ),
        migrations.AlterField(
            model_name="university",
            name="code",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Código de Institución"
            ),
        ),
        migrations.AlterField(
            model_name="university",
            name="name",
            field=models.CharField(
                max_length=255, verbose_name="Nombre de Institución"
            ),
        ),
    ]
