# Generated by Django 5.0.7 on 2025-10-08 18:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Browser",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID del Navegador",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        help_text="Browser's User-Agent string for identification.",
                        max_length=255,
                        verbose_name="Agente de Usuario",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Navegador Registrado",
                "verbose_name_plural": "Navegadores Registrados",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DirectChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_hidden_by_user1", models.BooleanField(default=False)),
                ("is_hidden_by_user2", models.BooleanField(default=False)),
                (
                    "user1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions_as_user1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions_as_user2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión de Chat Directo",
                "verbose_name_plural": "Sesiones de Chat Directo",
                "ordering": ["-updated_at"],
                "unique_together": {("user1", "user2")},
            },
        ),
        migrations.CreateModel(
            name="PushEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint",
                    models.URLField(
                        max_length=512, unique=True, verbose_name="URL del Endpoint"
                    ),
                ),
                ("keys", models.JSONField(verbose_name="Claves de Cifrado")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "browser",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_endpoint",
                        to="messaging.browser",
                        verbose_name="Navegador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Endpoint de Notificación Push",
                "verbose_name_plural": "Endpoints de Notificación Push",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SharedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.UUIDField()),
                ("title_snapshot", models.CharField(max_length=255)),
                ("description_snapshot", models.TextField(blank=True)),
                ("url_snapshot", models.URLField(max_length=2048)),
                ("shared_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_contents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contenido Compartido en Chat",
                "verbose_name_plural": "Contenidos Compartidos en Chat",
                "ordering": ["-shared_at"],
            },
        ),
        migrations.CreateModel(
            name="DirectMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_edited", models.BooleanField(default=False)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="messaging.directmessage",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_direct_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="messaging.directchatsession",
                    ),
                ),
                (
                    "shared_content",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="associated_messages",
                        to="messaging.sharedcontent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje Directo",
                "verbose_name_plural": "Mensajes Directos",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="Automatically generated descriptive name (e.g., 'Chrome on Windows').",
                        max_length=100,
                        verbose_name="Alias del Dispositivo",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Allows the user to disable notifications on this device without losing the subscription.",
                        verbose_name="Suscripción Activa",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "browser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_subscriptions",
                        to="messaging.browser",
                        verbose_name="Navegador",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscripción de Usuario",
                "verbose_name_plural": "Suscripciones de Usuario",
                "ordering": ["user", "-created_at"],
                "unique_together": {("user", "browser")},
            },
        ),
    ]
