# Generated by Django 5.0.7 on 2025-10-08 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Enter a clear and concise title for the announcement.",
                        max_length=200,
                        verbose_name="Título del Anuncio",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Write the full body of your announcement here.",
                        verbose_name="Contenido del Anuncio",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date and time the announcement was created (set automatically).",
                        verbose_name="Fecha de Creación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anuncio",
                "verbose_name_plural": "Anuncios",
                "ordering": ["-created_at"],
            },
        ),
    ]
