# Generated by Django 5.0.7 on 2025-11-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliveryNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extracted_vehicle_code",
                    models.CharField(
                        blank=True,
                        help_text="El código de vehículo exacto extraído por la IA, exista o no en la BBDD.",
                        max_length=50,
                        null=True,
                        verbose_name="Código de Vehículo Extraído",
                    ),
                ),
                (
                    "original_image",
                    models.ImageField(
                        upload_to="delivery_notes/%Y/%m/%d/",
                        verbose_name="Imagen Original del Albarán",
                    ),
                ),
                (
                    "processed_data",
                    models.JSONField(
                        blank=True,
                        help_text="Contiene toda la información extraída del albarán en formato JSON.",
                        null=True,
                        verbose_name="Datos Procesados del Albarán",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("needs_review", "Necesita Revisión"),
                            ("error", "Error de Procesamiento"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Subida"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Procesamiento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Albarán",
                "verbose_name_plural": "Albaranes",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        help_text="Ej: Furgoneta, Camión, Coche de servicio",
                        max_length=100,
                        verbose_name="Tipo de Vehículo",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código único del vehículo en formato LetraNumeroNumero, ej: A01",
                        max_length=10,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Matrícula"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehículo",
                "verbose_name_plural": "Vehículos",
                "ordering": ["code"],
            },
        ),
    ]
