# Generated by Django 5.0.7 on 2025-10-17 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_automation", "0009_pendingcontenttask_api_key_used_and_more"),
        ("delivery_note_processor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynote",
            name="api_key_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="content_automation.apikey",
                verbose_name="Clave de API Utilizada",
            ),
        ),
    ]
