# Generated by Django 5.0.7 on 2025-11-18 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("delivery_note_processor", "0001_initial"),
        ("orchestrator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynote",
            name="api_key_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orchestrator.apikey",
                verbose_name="Clave de API Utilizada",
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="delivery_note_processor.vehicle",
                verbose_name="Vehículo Asociado",
            ),
        ),
    ]
