# Generated by Django 5.0.7 on 2025-10-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery_note_processor", "0002_deliverynote_api_key_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynote",
            name="extracted_vehicle_code",
            field=models.CharField(
                blank=True,
                help_text="El código de vehículo exacto extraído por la IA, exista o no en la BBDD.",
                max_length=50,
                null=True,
                verbose_name="Código de Vehículo Extraído",
            ),
        ),
        migrations.AlterField(
            model_name="deliverynote",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("processing", "Procesando"),
                    ("completed", "Completado"),
                    ("needs_review", "Necesita Revisión"),
                    ("error", "Error de Procesamiento"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
