# Generated by Django 5.0.7 on 2025-11-15 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "delivery_note_processor",
            "0003_deliverynote_extracted_vehicle_code_and_more",
        ),
        ("orchestrator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverynote",
            name="api_key_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orchestrator.apikey",
                verbose_name="Clave de API Utilizada",
            ),
        ),
    ]
