# Generated by Django 5.0.7 on 2025-10-08 18:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicChatLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Identificador único para la URL de la sala de chat, generado automáticamente.",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Slug para URL",
                    ),
                ),
                (
                    "access_code",
                    models.CharField(
                        blank=True,
                        help_text="Código único para que usuarios no matriculados (invitados) puedan unirse a la sala.",
                        max_length=12,
                        unique=True,
                        verbose_name="Código de Acceso de Invitado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vínculo de Chat Académico",
                "verbose_name_plural": "Vínculos de Chat Académico",
                "ordering": ["subject__name"],
            },
        ),
        migrations.CreateModel(
            name="AcademicChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_username_display",
                    models.CharField(
                        max_length=150,
                        verbose_name="Nombre de usuario del remitente (para visualización)",
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenido del mensaje")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Marca de tiempo"
                    ),
                ),
                (
                    "is_deleted_by_moderator",
                    models.BooleanField(
                        default=False,
                        help_text="Marcado si el mensaje fue borrado por un moderador.",
                        verbose_name="¿Borrado por moderador?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de Chat Académico",
                "verbose_name_plural": "Mensajes de Chat Académico",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PendingEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        verbose_name="Email del usuario a matricular",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Matrícula Pendiente",
                "verbose_name_plural": "Matrículas Pendientes",
                "ordering": ["-created_at", "email"],
            },
        ),
    ]
