# Generated by Django 5.0.7 on 2025-10-08 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic_chat", "0001_initial"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicchatlink",
            name="chat_room",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_chat_link",
                to="chat.chatroom",
                verbose_name="Sala de Chat Asociada",
            ),
        ),
    ]
