# Generated by Django 5.0.7 on 2025-10-08 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic_chat", "0002_initial"),
        ("academic_structure", "0001_initial"),
        ("auth", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="academicchatlink",
            name="enrolled_students",
            field=models.ManyToManyField(
                blank=True,
                help_text="Usuarios verificados como alumnos para esta asignatura. Gestionado por administradores.",
                related_name="enrolled_in_academic_chats",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Alumnos Matriculados (Verificados)",
            ),
        ),
        migrations.AddField(
            model_name="academicchatlink",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Grupo que otorga acceso a esta sala de chat.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="academic_chat_links",
                to="auth.group",
                verbose_name="Grupo de Permisos",
            ),
        ),
        migrations.AddField(
            model_name="academicchatlink",
            name="subject",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_chat_link",
                to="academic_structure.subject",
                verbose_name="Asignatura Vinculada",
            ),
        ),
        migrations.AddField(
            model_name="academicchatmessage",
            name="chat_link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="academic_chat.academicchatlink",
                verbose_name="Vínculo de Chat Académico",
            ),
        ),
        migrations.AddField(
            model_name="academicchatmessage",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_academic_chat_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Remitente",
            ),
        ),
        migrations.AddField(
            model_name="pendingenrollment",
            name="academic_chat_link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pending_enrollments",
                to="academic_chat.academicchatlink",
                verbose_name="Vínculo de Chat Académico",
            ),
        ),
        migrations.AddField(
            model_name="pendingenrollment",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="added_pending_enrollments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Añadido por",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pendingenrollment",
            unique_together={("email", "academic_chat_link")},
        ),
    ]
