# Generated by Django 5.0.7 on 2025-10-08 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Escribe tu mensaje corto aquí (máx. 500 caracteres).",
                        verbose_name="Contenido del Mensaje",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Si no está marcado, solo tú podrás ver este mensaje en tu portafolio.",
                        verbose_name="¿Mensaje Público?",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="short_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje Corto del Portafolio",
                "verbose_name_plural": "Mensajes Cortos del Portafolio",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Ej: Mi perfil de GitHub, Blog Personal, LinkedIn",
                        max_length=100,
                        verbose_name="Título del Enlace",
                    ),
                ),
                (
                    "url",
                    models.URLField(max_length=2000, verbose_name="URL del Enlace"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enlace de Usuario del Portafolio",
                "verbose_name_plural": "Enlaces de Usuario del Portafolio",
                "ordering": ["created_at"],
            },
        ),
    ]
