# Generated by Django 5.0.7 on 2026-02-08 19:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("FREE", "Acceso Gratuito"),
                            ("PREMIUM", "Premium Individual"),
                            ("INSTITUTIONAL", "Licencia Institucional"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Nombre del Plan",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "daily_exam_limit",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Límite Diario de Exámenes"
                    ),
                ),
                (
                    "weekly_exam_limit",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Límite Semanal de Exámenes"
                    ),
                ),
                (
                    "can_access_c_level",
                    models.BooleanField(
                        default=False, verbose_name="Acceso a Nivel C (Maestro)"
                    ),
                ),
                (
                    "can_use_specialized_archetypes",
                    models.BooleanField(
                        default=False, verbose_name="Acceso a Arquetipos Especializados"
                    ),
                ),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=6,
                        verbose_name="Precio Mensual (€)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Plan de Suscripción",
                "verbose_name_plural": "Planes de Suscripción",
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "archetype_id",
                    models.CharField(max_length=50, verbose_name="ID Arquetipo"),
                ),
                (
                    "sub_archetype_id",
                    models.CharField(max_length=50, verbose_name="ID Sub-Arquetipo"),
                ),
                (
                    "itinerary_id",
                    models.CharField(max_length=50, verbose_name="ID Itinerario"),
                ),
                (
                    "pedagogical_level",
                    models.CharField(max_length=20, verbose_name="Nivel Pedagógico"),
                ),
                (
                    "structure",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Estructura del Examen"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("GENERATING", "Generando"),
                            ("READY", "Listo"),
                            ("IN_PROGRESS", "En Progreso"),
                            ("COMPLETED", "Completado"),
                            ("GRADING", "Corrigiendo"),
                            ("GRADED", "Calificado"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "error_log",
                    models.TextField(
                        blank=True, null=True, verbose_name="Log de Error"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams_v2",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Examen (V2)",
                "verbose_name_plural": "Exámenes (V2)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CostLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(max_length=50, verbose_name="Tipo de Operación"),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="Modelo IA"),
                ),
                (
                    "input_tokens",
                    models.PositiveIntegerField(verbose_name="Tokens Entrada"),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(verbose_name="Tokens Salida"),
                ),
                (
                    "cost_usd",
                    models.DecimalField(
                        decimal_places=6, max_digits=10, verbose_name="Coste (USD)"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_logs",
                        to="assessment_v2.exam",
                        verbose_name="Examen Relacionado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Coste Detallado",
                "verbose_name_plural": "Logs de Coste Detallados",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_responses",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Respuestas del Estudiante"
                    ),
                ),
                (
                    "grading_report",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Informe de Calificación"
                    ),
                ),
                (
                    "final_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Nota Final",
                    ),
                ),
                ("passed", models.BooleanField(default=False, verbose_name="Aprobado")),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Entregado"),
                ),
                (
                    "graded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Calificado"
                    ),
                ),
                (
                    "exam",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission",
                        to="assessment_v2.exam",
                        verbose_name="Examen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrega de Examen",
                "verbose_name_plural": "Entregas de Exámenes",
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Inicio"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Finalización"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Suscripción Activa"
                    ),
                ),
                (
                    "auto_renew",
                    models.BooleanField(
                        default=False, verbose_name="Renovación Automática"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assessment_v2.subscriptionplan",
                        verbose_name="Plan Actual",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_subscription",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscripción de Usuario",
                "verbose_name_plural": "Suscripciones de Usuarios",
            },
        ),
        migrations.CreateModel(
            name="TokenUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Fecha")),
                (
                    "input_tokens_total",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tokens de Entrada"
                    ),
                ),
                (
                    "output_tokens_total",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tokens de Salida"
                    ),
                ),
                (
                    "estimated_cost_usd",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Coste Estimado (USD)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uso Diario de Tokens",
                "verbose_name_plural": "Registros de Uso Diario",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
