# Generated by Django 5.0.7 on 2026-02-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_v2", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="can_access_c_level",
            field=models.BooleanField(
                default=True, verbose_name="Acceso a Nivel C (Maestro)"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="can_use_specialized_archetypes",
            field=models.BooleanField(
                default=True, verbose_name="Acceso a Arquetipos Especializados"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="name",
            field=models.CharField(
                choices=[
                    ("FREE", "Gratuito"),
                    ("BRONCE", "Bronce"),
                    ("PLATA", "Plata"),
                    ("ORO", "Oro"),
                    ("PLATINO", "Platino"),
                    ("DIOS", "Nivel Dios"),
                ],
                max_length=50,
                unique=True,
                verbose_name="Nombre del Plan",
            ),
        ),
    ]
