# Generated by Django 5.0.7 on 2026-02-14 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_v2", "0002_alter_subscriptionplan_can_access_c_level_and_more"),
        (
            "contents",
            "0019_userstudynavigation_alter_discipline_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="content_copy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="contents.contentcopy",
                verbose_name="Copia de Estudio",
            ),
        ),
    ]
