# Generated by Django 5.0.7 on 2026-02-15 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_v2", "0003_exam_content_copy"),
        (
            "contents",
            "0019_userstudynavigation_alter_discipline_unique_together_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="structure",
        ),
        migrations.AddField(
            model_name="exam",
            name="grading_params",
            field=models.JSONField(default=dict, verbose_name="Parámetros de Rigor"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="content_copy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="contents.contentcopy",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="exam",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("GENERATING", "Generando"),
                    ("READY", "Listo"),
                    ("IN_PROGRESS", "En Progreso"),
                    ("COMPLETED", "Completado"),
                    ("GRADING", "Corrigiendo"),
                    ("GRADED", "Calificado"),
                    ("ERROR", "Error"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="exam",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams_v2",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="exam",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submission",
                to="assessment_v2.exam",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="final_score",
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="graded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="grading_report",
            field=models.JSONField(null=True, verbose_name="Informe de Calificación"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="passed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="submission",
            name="student_responses",
            field=models.JSONField(null=True, verbose_name="Respuestas del Estudiante"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submitted_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="ExamSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subdivision_id", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("instructions", models.TextField()),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        default=0, help_text="Límite en segundos."
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="assessment_v2.exam",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ExamItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_type", models.CharField(max_length=50)),
                ("widget_id", models.CharField(max_length=50)),
                ("content", models.JSONField(verbose_name="Contenido del Ítem")),
                (
                    "grading_logic",
                    models.JSONField(verbose_name="Lógica de Calificación"),
                ),
                ("metadata", models.JSONField(verbose_name="Metadatos Pedagógicos")),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="assessment_v2.examsection",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
