# Generated by Django 5.0.7 on 2026-02-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_v2", "0004_remove_exam_structure_exam_grading_params_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="event_log",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Log de Eventos"
            ),
        ),
    ]
