# Generated by Django 5.0.7 on 2026-02-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_v2", "0005_exam_event_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="costlog",
            name="api_key_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Clave API"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="immersion_mode",
            field=models.CharField(
                default="VEHICULAR", max_length=20, verbose_name="Modo de Inmersión"
            ),
        ),
    ]
