# Generated by Django 5.0.7 on 2026-02-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_v2", "0006_costlog_api_key_name_exam_immersion_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="expiration_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Caducidad"
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("GENERATING", "Generando"),
                    ("READY", "Listo"),
                    ("IN_PROGRESS", "En Progreso"),
                    ("COMPLETED", "Completado"),
                    ("GRADING", "Corrigiendo"),
                    ("GRADED", "Calificado"),
                    ("ERROR", "Error"),
                    ("EXPIRED_UNTAKEN", "Caducado (No realizado)"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
