# Generated by Django 5.0.7 on 2026-02-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_v2", "0007_exam_expiration_date_alter_exam_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="examsection",
            name="layout_mode",
            field=models.CharField(
                default="STANDARD",
                help_text="Define si la sección necesita panel lateral (SPLIT_TEXT, SPLIT_VISUAL) o pantalla completa (STANDARD).",
                max_length=20,
                verbose_name="Modo de Layout",
            ),
        ),
        migrations.AddField(
            model_name="examsection",
            name="section_stimulus",
            field=models.TextField(
                blank=True,
                help_text="Texto, HTML o URL base. Usado en lectura (Reading), casos prácticos, o datos compartidos.",
                null=True,
                verbose_name="Estímulo de Sección",
            ),
        ),
    ]
