# Generated by Django 5.0.7 on 2026-02-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_v2", "0008_examsection_layout_mode_examsection_section_stimulus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="archetype_id",
            field=models.CharField(
                choices=[
                    ("ARCH_LANG", "Lenguas Extranjeras"),
                    ("ARCH_HEALTH", "Ciencias de la Salud"),
                    ("ARCH_TECH", "Ciencias Técnicas e Ingeniería"),
                    ("ARCH_SOC", "Ciencias Sociales y Jurídicas"),
                    ("ARCH_HUM", "Artes y Humanidades"),
                ],
                max_length=50,
                verbose_name="ID Arquetipo",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="immersion_mode",
            field=models.CharField(
                choices=[
                    ("VEHICULAR", "Idioma Vehicular"),
                    ("BILINGUAL", "Bilingüe"),
                    ("TOTAL", "Inmersión Total"),
                ],
                default="VEHICULAR",
                max_length=20,
                verbose_name="Modo de Inmersión",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="itinerary_id",
            field=models.CharField(
                choices=[
                    ("ITIN_MAI", "Maior / Especialización"),
                    ("ITIN_MIN", "Minor / Transversal"),
                    ("ITIN_ROT", "Rotatorio Clínico"),
                    ("ITIN_PROF", "Profesional / Ingeniería"),
                    ("ITIN_INV", "Investigador"),
                    ("ITIN_DOC", "Docente / Didáctico"),
                ],
                max_length=50,
                verbose_name="ID Itinerario",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="pedagogical_level",
            field=models.CharField(
                choices=[
                    ("LVL_A", "Acceso / Fundamentos"),
                    ("LVL_B", "Independiente / Aplicación"),
                    ("LVL_C", "Maestro / Crítico"),
                ],
                max_length=20,
                verbose_name="Nivel Pedagógico",
            ),
        ),
        migrations.AlterField(
            model_name="examsection",
            name="layout_mode",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Ancho Completo"),
                    ("SPLIT_TEXT", "Panel Lateral de Texto"),
                    ("SPLIT_VISUAL", "Panel Lateral Visual"),
                ],
                default="STANDARD",
                help_text="Define si la sección necesita panel lateral (SPLIT_TEXT, SPLIT_VISUAL) o pantalla completa (STANDARD).",
                max_length=20,
                verbose_name="Modo de Layout",
            ),
        ),
    ]
