# Generated by Django 5.0.7 on 2026-02-27 04:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessment_v2",
            "0009_alter_exam_archetype_id_alter_exam_immersion_mode_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="target_language_code",
            field=models.CharField(
                default="es",
                help_text="ISO 639-1 (ej: en, fr, ja)",
                max_length=10,
                verbose_name="Código de Idioma",
            ),
        ),
        migrations.AddField(
            model_name="examitem",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="exam",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
