# Generated by Django 5.0.7 on 2026-02-27 04:44

from django.db import migrations


import uuid

def gen_uuid(apps, schema_editor):
    ExamItem = apps.get_model('assessment_v2', 'ExamItem')
    for row in ExamItem.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ("assessment_v2", "0010_exam_target_language_code_examitem_uuid_and_more"),
    ]

    operations =[
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
