# Generated by Django 5.0.7 on 2026-02-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_v2", "0012_alter_exam_uuid_alter_examitem_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examitem",
            name="content",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Contenido del Ítem"
            ),
        ),
        migrations.AlterField(
            model_name="examitem",
            name="grading_logic",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Lógica de Calificación"
            ),
        ),
        migrations.AlterField(
            model_name="examitem",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Metadatos Pedagógicos"
            ),
        ),
    ]
