# Generated by Django 5.0.7 on 2026-02-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessment_v2",
            "0013_alter_examitem_content_alter_examitem_grading_logic_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="localized_sections",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Secciones Localizadas"
            ),
        ),
    ]
