# Generated by Django 5.0.7 on 2026-02-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_v2", "0014_exam_localized_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="examitem",
            name="estimated_time",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Tiempo Estimado (s)"
            ),
        ),
        migrations.AddField(
            model_name="examitem",
            name="level_requisite",
            field=models.CharField(
                default="Mandatory",
                help_text="[Mandatory | Optional | Advanced]",
                max_length=20,
                verbose_name="Requisito de Nivel",
            ),
        ),
        migrations.AddField(
            model_name="examitem",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=3,
                verbose_name="Peso Relativo",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="archetype_id",
            field=models.CharField(
                choices=[
                    ("ARCH_LANG", "Lenguas Extranjeras"),
                    ("ARCH_HEALTH", "Ciencias de la Salud"),
                    ("ARCH_TECH", "Ciencias Técnicas e Ingeniería"),
                    ("ARCH_SOC", "Ciencias Sociales y Jurídicas"),
                    ("ARCH_HUM", "Artes y Humanidades"),
                    ("ARCH_SCI", "Ciencias Puras y Experimentales"),
                ],
                max_length=50,
                verbose_name="ID Arquetipo",
            ),
        ),
    ]
