# Generated by Django 5.0.7 on 2026-03-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_v2", "0016_alter_exam_sub_archetype_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examitem",
            name="fail_logic",
            field=models.CharField(
                choices=[
                    ("PENALTY", "Penalización Estándar"),
                    ("FATAL", "Error Fatal (Muerte Súbita)"),
                    ("PARTIAL", "Crédito Parcial"),
                ],
                default="PENALTY",
                max_length=20,
                verbose_name="Lógica de Fallo",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="sub_archetype_id",
            field=models.CharField(
                choices=[
                    ("SUB-LIN-INSTR", "Modelo Instrumental"),
                    ("SUB-LIN-MINOR", "Modelo Minor/Iniciación"),
                    ("SUB-LIN-PHILO", "Modelo Filológico"),
                    ("SUB-LIN-NORM", "Modelo Norma y Uso"),
                    ("SUB-LIN-TRA-TECH", "Traducción Profesional"),
                    ("SUB-LIN-TRA-LIT", "Traducción Literaria"),
                    ("SUB-HUM-HIST", "Modelo Historiográfico"),
                    ("SUB-HUM-PHIL", "Modelo Dialéctico"),
                    ("SUB-HUM-ART-HIST", "Modelo Iconográfico"),
                    ("SUB-HUM-ART-CREA", "Modelo Bellas Artes"),
                    ("SUB-HUM-MUS", "Modelo Musicología"),
                    ("SUB-HUM-ANTH", "Modelo Antropológico"),
                    ("SUB-SAN-MED-CLIN", "Diagnóstico Diferencial y Clínica"),
                    ("SUB-SAN-MED-BASIC", "Básicas Médicas"),
                    ("SUB-SAN-ODON", "Odontología"),
                    ("SUB-SAN-FISIO", "Fisioterapia"),
                    ("SUB-SAN-CUID", "Enfermería y Cuidados"),
                    ("SUB-SAN-LAB", "Bioquímica y Farmacia"),
                    ("SUB-SAN-PSY-CLIN", "Psicología Clínica"),
                    ("SUB-SAN-PSY-EXP", "Psicología Experimental"),
                    ("SUB-SAN-VET", "Veterinaria"),
                    ("SUB-SAN-NUT", "Nutrición y Dietética"),
                    ("SUB-SOC-LAW-PROC", "Derecho Procesal"),
                    ("SUB-SOC-LAW-DICT", "Derecho Civil/Penal (Dictamen)"),
                    ("SUB-SOC-ECON-QUAN", "Economía Cuantitativa"),
                    ("SUB-SOC-ECON-MGMT", "Organización de Empresas"),
                    ("SUB-SOC-EDU-KIDS", "Magisterio (Infantil/Primaria)"),
                    ("SUB-SOC-EDU-SEC", "Profesorado (Secundaria)"),
                    ("SUB-SOC-COMM-JOUR", "Periodismo"),
                    ("SUB-SOC-COMM-AV", "Comunicación Audiovisual"),
                    ("SUB-SOC-GEOG", "Geografía"),
                    ("SUB-SOC-WORK", "Trabajo Social"),
                    ("SUB-TEC-SOFT", "Ingeniería Informática/Software"),
                    ("SUB-TEC-CIVIL", "Ingeniería Civil/Caminos"),
                    ("SUB-TEC-INDUS", "Ingeniería Industrial"),
                    ("SUB-TEC-CHEM", "Ingeniería Química"),
                    ("SUB-TEC-PROJ", "Arquitectura (Proyecto)"),
                    ("SUB-TEC-CONS", "Edificación y Construcción"),
                    ("SUB-TEC-PURE", "Física y Matemáticas Puras"),
                    ("SUB-SCI-BIO", "Biología"),
                    ("SUB-SCI-CHEM", "Química"),
                    ("SUB-SCI-PHYS", "Física Aplicada"),
                    ("SUB-SCI-GEOL", "Geología"),
                    ("SUB-SCI-ENV", "Ciencias Ambientales"),
                    ("SUB-SCI-DATA", "Ciencia de Datos"),
                ],
                max_length=50,
                verbose_name="ID Sub-Arquetipo",
            ),
        ),
        migrations.AlterField(
            model_name="examitem",
            name="level_requisite",
            field=models.CharField(
                choices=[
                    ("MANDATORY", "Obligatorio"),
                    ("OPTIONAL", "Opcional"),
                    ("ADVANCED", "Avanzado"),
                ],
                default="MANDATORY",
                max_length=20,
                verbose_name="Requisito de Nivel",
            ),
        ),
    ]
