# Generated by Django 5.0.7 on 2026-03-07 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessment_v2",
            "0017_examitem_fail_logic_alter_exam_sub_archetype_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="is_sequential",
            field=models.BooleanField(
                default=False,
                help_text="Impide el retroceso a secciones anteriores. Requisito ARCH_LANG.",
                verbose_name="Secuencial Obligatorio",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="section_scores",
            field=models.JSONField(
                help_text="Evalúa criterios de éxito y umbrales mínimos por destreza (ej. 50% en ARCH_LANG).",
                null=True,
                verbose_name="Calificaciones por Sección",
            ),
        ),
        migrations.AlterField(
            model_name="examitem",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("PRM-STRIKE", "Respuesta Múltiple (Penalización Progresiva)"),
                    ("RBT-CANON", "Respuesta Breve (Precisión Terminológica)"),
                    ("RPP_TRAZA", "Resolución Procedimental (Arrastre Error)"),
                    ("DEMO-PROOF", "Demostración Formal Axiomática"),
                    ("BLUEPRINT-DESIGN", "Diseño de Planos y Esquemas"),
                    ("CDS-KILL", "Checklist Dicotómico Crítico"),
                    ("DRA-HOLO", "Disertación (Rúbrica Holística)"),
                    ("BMT-SHIFT", "Mediación y Transferencia de Registro"),
                    ("ILC-CONTEXT", "Interpretación de Contexto y Datos Brutos"),
                    ("EV-PALE", "Transcripción y Exégesis de Fuentes Primarias"),
                    ("LIKERT-SCALE", "Escala de Desempeño ECOE/Likert"),
                    ("JUDICIAL-SIM", "Simulación de Juicio/Procedimiento"),
                    ("CLO-OPEN", "Open Cloze / Rellenado Abierto"),
                    ("CLO-MULTI", "Multiple Choice Cloze / Rellenado Selectivo"),
                    ("MAT-LINK", "Matching / Emparejamiento"),
                    ("DIA-INTERACT", "Interacción Dialéctica (UniversIA)"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="examitem",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="Peso Relativo",
            ),
        ),
    ]
