# Generated by Django 5.0.7 on 2026-03-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_v2", "0018_exam_is_sequential_submission_section_scores_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="is_sequential",
            field=models.BooleanField(
                default=False,
                help_text="Impide el retroceso a secciones anteriores una vez completadas.",
                verbose_name="Secuencial Obligatorio",
            ),
        ),
        migrations.AlterField(
            model_name="examitem",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("PRM-STRIKE", "Respuesta Múltiple (Penalización Progresiva)"),
                    ("RBT-CANON", "Respuesta Breve (Precisión Terminológica)"),
                    ("RPP-TRAZA", "Resolución Procedimental (Arrastre Error)"),
                    ("CDS-KILL", "Checklist Dicotómico Crítico"),
                    ("DRA-HOLO", "Disertación (Rúbrica Holística)"),
                    ("BMT-SHIFT", "Mediación y Transferencia de Registro"),
                    ("ILC-CONTEXT", "Interpretación de Contexto y Datos Brutos"),
                    ("EV-PALE", "Transcripción y Exégesis de Fuentes Primarias"),
                    ("CLO-OPEN", "Open Cloze / Rellenado Abierto"),
                    ("CLO-MULTI", "Multiple Choice Cloze / Rellenado Selectivo"),
                    ("MAT-LINK", "Matching / Emparejamiento"),
                    ("DIA-INTERACT", "Interacción Dialéctica (UniversIA)"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="section_scores",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Calificaciones por Sección"
            ),
        ),
    ]
