# Generated by Django 5.0.7 on 2026-05-16 17:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessment_v2",
            "0019_alter_exam_is_sequential_alter_examitem_block_type_and_more",
        ),
        ("contents", "0021_fix_user_nav_cascade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="examitem",
            options={
                "ordering": ["order"],
                "verbose_name": "Ítem de Examen",
                "verbose_name_plural": "Ítems de Examen",
            },
        ),
        migrations.AlterModelOptions(
            name="examsection",
            options={
                "ordering": ["order"],
                "verbose_name": "Sección de Examen",
                "verbose_name_plural": "Secciones de Examen",
            },
        ),
        migrations.AlterField(
            model_name="exam",
            name="archetype_id",
            field=models.CharField(
                choices=[
                    ("ARCH_LANG", "Lenguas Extranjeras (Instrumental/CLM)"),
                    ("ARCH_HEALTH", "Ciencias de la Salud (ECOE)"),
                    ("ARCH_TECH", "Ciencias Técnicas e Ingeniería (Resolutivo)"),
                    ("ARCH_SOC", "Ciencias Sociales y Jurídicas (Casuístico)"),
                    ("ARCH_HUM", "Artes y Humanidades (Hermenéutico)"),
                    ("ARCH_SCI", "Ciencias Puras y Experimentales (Metodológico)"),
                ],
                max_length=20,
                verbose_name="ID Arquetipo",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="content_copy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="contents.contentcopy",
                verbose_name="Copia de Estudio",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="expiration_date",
            field=models.DateTimeField(
                blank=True,
                help_text="24h tras el estado READY. Penalización total si no se realiza.",
                null=True,
                verbose_name="Fecha de Caducidad",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="grading_params",
            field=models.JSONField(
                default=dict,
                help_text="Rigor factor y penalty_threshold calculados al crear el examen.",
                verbose_name="Parámetros de Rigor",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="immersion_mode",
            field=models.CharField(
                choices=[
                    ("VEHICULAR", "Idioma Vehicular (Castellano)"),
                    ("BILINGUAL", "Bilingüe (Castellano + Idioma Objetivo)"),
                    ("TOTAL", "Inmersión Total (Idioma Objetivo Dinámico)"),
                ],
                default="VEHICULAR",
                max_length=20,
                verbose_name="Modo de Inmersión",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="is_sequential",
            field=models.BooleanField(
                default=False,
                help_text="Si True, impide el retroceso a secciones anteriores (Non-Backtracking).",
                verbose_name="Secuencial Obligatorio",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="itinerary_id",
            field=models.CharField(
                choices=[
                    (
                        "ITIN_MAI",
                        "Maior / Especialización de Grado (Nivel Catedrático)",
                    ),
                    ("ITIN_MIN", "Minor / Mención Transversal (Nivel Competente)"),
                    ("ITIN_ROT", "Rotatorio Clínico / Seguridad (Dicotómico)"),
                    ("ITIN_PROF", "Profesional / Ingeniería (Normativo-Ejecutivo)"),
                    ("ITIN_INV", "Investigador / Académico (Metodológico)"),
                    ("ITIN_DOC", "Docente / Didáctico (Transpositivo)"),
                ],
                default="ITIN_MIN",
                max_length=20,
                verbose_name="ID Itinerario",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="localized_sections",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Títulos e instrucciones traducidos al idioma objetivo (solo ARCH_LANG).",
                verbose_name="Secciones Localizadas",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="pedagogical_level",
            field=models.CharField(
                choices=[
                    ("LVL_A", "Acceso / Fundamentos (A1-A2): Descriptivo"),
                    ("LVL_B", "Independiente / Aplicación (B1-B2): Procedimental"),
                    ("LVL_C", "Maestro / Crítico (C1-C2): Epistemológico"),
                ],
                default="LVL_B",
                max_length=10,
                verbose_name="Nivel Pedagógico",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("GENERATING", "Generando"),
                    ("READY", "Listo para realizar"),
                    ("IN_PROGRESS", "En Progreso"),
                    ("GRADING", "Corrigiendo"),
                    ("GRADED", "Calificado"),
                    ("ERROR", "Error de Generación"),
                    ("EXPIRED_UNTAKEN", "Caducado (No realizado)"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="sub_archetype_id",
            field=models.CharField(
                choices=[
                    ("SUB-LIN-INSTR", "Instrumental / CertAcles CLM-UGR"),
                    ("SUB-LIN-MINOR", "Minor / Iniciación (Lengua B/C)"),
                    ("SUB-LIN-PHILO", "Filológico / Lingüística Histórica"),
                    ("SUB-LIN-ECDO", "Ecdótica / Edición y Crítica Textual"),
                    ("SUB-LIN-NORM", "Norma y Uso / El Español Actual"),
                    ("SUB-LIN-TRA-TECH", "Traducción Especializada B-A Inglés"),
                    (
                        "SUB-LIN-TRA-LIT",
                        "Traducción Literaria / Literatura y Traducción",
                    ),
                    ("SUB-HUM-HIST", "Historiográfico (Historia UGR)"),
                    ("SUB-HUM-PHIL", "Dialéctico (Filosofía UGR)"),
                    ("SUB-HUM-ART-HIST", "Iconográfico (Historia del Arte UGR)"),
                    (
                        "SUB-HUM-ART-CREA",
                        "Bellas Artes — Emulación Parcial Certificada",
                    ),
                    (
                        "SUB-HUM-MUS",
                        "Musicológico (Historia y Ciencias de la Música UGR)",
                    ),
                    ("SUB-HUM-ANTH", "Antropológico — Subarquetipo Transversal"),
                    (
                        "SUB-SAN-MED-CLIN",
                        "Diagnóstico Clínico y Razonamiento (Medicina UGR)",
                    ),
                    (
                        "SUB-SAN-MED-BASIC",
                        "Ciencias Básicas Médicas: Anatomía e Histología",
                    ),
                    (
                        "SUB-SAN-MED-FISIO-GEN",
                        "Fisiología General y Médica (Medicina UGR)",
                    ),
                    (
                        "SUB-SAN-MED-FISIO-NEURO",
                        "Fisiología Neurológica (Medicina UGR)",
                    ),
                    ("SUB-SAN-CUID", "Cuidados / Enfermería NANDA (UGR)"),
                    ("SUB-SAN-ODON", "Odontología — Emulación Parcial Certificada"),
                    ("SUB-SAN-FISIO", "Fisioterapia — Emulación Parcial Certificada"),
                    (
                        "SUB-SAN-BIOQUIM",
                        "Bioquímica Metabólica (Farmacia UGR) — EP Cert.",
                    ),
                    ("SUB-SAN-FARM", "Farmacología I y II (Farmacia UGR)"),
                    ("SUB-SAN-PSY-DIAG", "Psicopatología del Adulto (Psicología UGR)"),
                    (
                        "SUB-SAN-PSY-EVAL",
                        "Evaluación Psicológica: Técnicas y Aplicaciones",
                    ),
                    ("SUB-SAN-PSY-MET", "Métodos y Diseños (Psicología UGR)"),
                    (
                        "SUB-SAN-PSY-STAT",
                        "Descripción y Exploración de Datos (Psicología)",
                    ),
                    ("SUB-SAN-VET-CLIN", "Veterinaria Clínica (UCO) — EP Certificada"),
                    ("SUB-SAN-VET-CIR", "Cirugía Veterinaria (UCO) — EP Certificada"),
                    ("SUB-SAN-NUT-DIET", "Dietética y Nutrición Clínica (UGR)"),
                    (
                        "SUB-SAN-NUT-BROM",
                        "Bromatología (Nutrición UGR) — EP Certificada",
                    ),
                    (
                        "SUB-SAN-NUT-SPUB",
                        "Salud Pública y Alimentación en Colectividades",
                    ),
                    ("SUB-SOC-LAW-PROC-CIV", "Derecho Procesal Civil (UGR)"),
                    ("SUB-SOC-LAW-PROC-PEN", "Derecho Procesal Penal (UGR)"),
                    ("SUB-SOC-LAW-DICT-CIV", "Derecho Civil I-IV — Dictamen (UGR)"),
                    ("SUB-SOC-LAW-DICT-PEN", "Derecho Penal I-II — Dictamen (UGR)"),
                    (
                        "SUB-SOC-ECON-QUAN-STAT",
                        "Estadística y Técnicas Cuantitativas (UGR)",
                    ),
                    ("SUB-SOC-ECON-QUAN-ECON", "Econometría I-III (Economía UGR)"),
                    (
                        "SUB-SOC-ECON-MGMT-ACC",
                        "Contabilidad Financiera y de Gestión (UGR)",
                    ),
                    ("SUB-SOC-ECON-MGMT-STR", "Dirección Estratégica I-II (ADE UGR)"),
                    ("SUB-SOC-ECON-MGMT-ECO", "Microeconomía y Macroeconomía (UGR)"),
                    ("SUB-SOC-EDU-KIDS", "Magisterio Infantil/Primaria DUA (UGR)"),
                    ("SUB-SOC-EDU-SEC", "Máster Profesorado Secundaria MAES (UGR)"),
                    ("SUB-SOC-COMM-JOUR", "Periodismo y Redacción (UGR)"),
                    ("SUB-SOC-COMM-AV", "Comunicación Audiovisual y Guion (UGR)"),
                    ("SUB-SOC-GEOG-SIG", "Sistemas de Información Geográfica (UGR)"),
                    ("SUB-SOC-GEOG-TER", "Geografía Humana y Territorial (UGR)"),
                    ("SUB-SOC-GEOG-FIS", "Geografía Física y Climatología (UGR)"),
                    (
                        "SUB-SOC-WORK-INT",
                        "Trabajo Social: Intervención Individual/Familiar",
                    ),
                    ("SUB-SOC-WORK-POL", "Trabajo Social: Política Social y Bienestar"),
                    (
                        "SUB-SOC-WORK-MED",
                        "Trabajo Social: Mediación y Ámbitos Especializados",
                    ),
                    (
                        "SUB-TEC-SOFT-ALG",
                        "Algoritmia y Estructuras de Datos (ETSIIT-UGR)",
                    ),
                    ("SUB-TEC-SOFT-DS", "Diseño de Software e Ingeniería (ETSIIT-UGR)"),
                    ("SUB-TEC-SOFT-SE", "Ingeniería del Software (ETSIIT-UGR)"),
                    (
                        "SUB-TEC-CIVIL-STRUCT",
                        "Estructuras de Edificación (ETSICCP-UGR)",
                    ),
                    (
                        "SUB-TEC-CIVIL-CONC",
                        "Hormigón Armado y Pretensado (ETSICCP-UGR)",
                    ),
                    ("SUB-TEC-CIVIL-STEEL", "Estructuras Metálicas (ETSICCP-UGR)"),
                    ("SUB-TEC-INDUS-THERMO", "Termodinámica y Motores (EPSC-UCO)"),
                    ("SUB-TEC-INDUS-TMM", "Teoría de Máquinas y Mecanismos (EPSC-UCO)"),
                    (
                        "SUB-TEC-INDUS-DEM",
                        "Diseño y Fabricación — Ingeniería Industrial (UCO)",
                    ),
                    ("SUB-TEC-CHEM-BAL", "Balances de Materia y Energía (IQ-UGR)"),
                    ("SUB-TEC-CHEM-REACT", "Ingeniería de Reactores Químicos (IQ-UGR)"),
                    ("SUB-TEC-PROJ-ARCH", "Proyectos de Arquitectura (ETSAG-UGR)"),
                    (
                        "SUB-TEC-PROJ-URB",
                        "Urbanismo y Ordenación del Territorio (ETSAG-UGR)",
                    ),
                    ("SUB-TEC-CONS-TECH", "Tecnología de la Construcción (ETSIE-UGR)"),
                    (
                        "SUB-TEC-CONS-MAN",
                        "Gestión y Economía de la Construcción (ETSIE-UGR)",
                    ),
                    (
                        "SUB-TEC-PURE-ANAL",
                        "Análisis Matemático (Grado Matemáticas UGR)",
                    ),
                    (
                        "SUB-TEC-PURE-ALGSTR",
                        "Álgebra Estructural y Topología (Matemáticas UGR)",
                    ),
                    ("SUB-SCI-BIO-GEN", "Biología Molecular y Genética (UGR)"),
                    ("SUB-SCI-BIO-ZOO", "Zoología y Botánica (UGR)"),
                    ("SUB-SCI-BIO-ECO", "Ecología (UGR)"),
                    ("SUB-SCI-CHEM-ORG", "Química Orgánica Pura (UGR)"),
                    ("SUB-SCI-CHEM-INORG", "Química Inorgánica Pura (UGR)"),
                    ("SUB-SCI-PHYS-EM", "Electromagnetismo (Física UGR)"),
                    ("SUB-SCI-PHYS-QM", "Mecánica Cuántica (Física UGR)"),
                    ("SUB-SCI-GEOL-MIN", "Mineralogía y Petrología (UGR)"),
                    ("SUB-SCI-GEOL-STRAT", "Estratigrafía (UGR)"),
                    ("SUB-SCI-GEOL-MAP", "Cartografía Geológica (UGR)"),
                    ("SUB-SCI-ENV-RES", "Gestión de Residuos y Recursos (UGR)"),
                    ("SUB-SCI-ENV-CONT", "Contaminación Ambiental (UGR)"),
                    (
                        "SUB-SCI-DATA-STAT",
                        "Estadística Computacional e Inferencia (UCM GIDIA)",
                    ),
                    ("SUB-SCI-DATA-ML", "Aprendizaje Automático e IA (UCM GIDIA)"),
                    ("SUB-SCI-DATA-BIG", "Ingeniería de Datos y Big Data (UCM GIDIA)"),
                ],
                max_length=50,
                verbose_name="ID Sub-Arquetipo",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="target_language_code",
            field=models.CharField(
                default="es",
                help_text="ISO 639-1 (ej: en, fr, ja, ar). Solo relevante para ARCH_LANG.",
                max_length=10,
                verbose_name="Código ISO de Idioma Objetivo",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams_v2",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AlterField(
            model_name="examitem",
            name="block_type",
            field=models.CharField(
                choices=[
                    (
                        "PRM-STRIKE",
                        "Respuesta Múltiple con Penalización — Fórmula UGR [A-E/(N-1)]",
                    ),
                    (
                        "RBT-CANON",
                        "Respuesta Breve de Precisión Terminológica — Sin Paráfrasis",
                    ),
                    (
                        "RBT-SHORT-LANG",
                        "Respuesta Breve Lingüística ≤4 palabras (CertAcles/CLM-UGR)",
                    ),
                    (
                        "RPP-TRAZA",
                        "Resolución Procedimental con Arrastre de Error — Multietapa",
                    ),
                    (
                        "CDS-KILL",
                        "Checklist Dicotómico de Seguridad Crítica — KILL_SWITCH",
                    ),
                    ("DRA-HOLO", "Rúbrica Analítica Holística — 4 Ejes UGR/CertAcles"),
                    (
                        "DRA-HOLO-LIT",
                        "Rúbrica Holística Literaria — 4 Ejes TRA-LIT FTI-UGR",
                    ),
                    (
                        "BMT-SHIFT",
                        "Mediación y Transferencia de Registro — Fidelidad + Adecuación",
                    ),
                    (
                        "ILC-CONTEXT",
                        "Interpretación de Contexto y Datos Brutos (IA-Evaluado)",
                    ),
                    (
                        "EV-PALE",
                        "Transcripción y Exégesis de Fuentes Primarias (Paleografía)",
                    ),
                    (
                        "EV-DIAC-VAL",
                        "Motor Diacrónico — Evolución Fonética (Philo UGR)",
                    ),
                    (
                        "EV-NORM-ANALYSIS",
                        "Motor Panhispánico — Desviaciones Norma (Norm UGR)",
                    ),
                    (
                        "EV-TRA-PRECISION",
                        "Motor Precisión Terminológica Traductológica",
                    ),
                    (
                        "EV-TRA-PRECISION-TECH",
                        "Motor Precisión FTI-UGR — Jerarquía Errores A/B/C",
                    ),
                    (
                        "EV-ICON-ART",
                        "Motor Iconológico — Identificación + Panofsky (ART-HIST)",
                    ),
                    (
                        "EV-MUS-ANAL",
                        "Motor de Análisis Musical Armónico-Formal (HUM-MUS)",
                    ),
                    (
                        "CLO-OPEN",
                        "Open Cloze / Rellenado Abierto — Validación Léxico-Morfológica",
                    ),
                    (
                        "CLO-MULTI",
                        "Multiple Choice Cloze / Rellenado Selectivo — Distractores",
                    ),
                    ("MAT-LINK", "Matching / Emparejamiento — Drag & Drop Vinculación"),
                    (
                        "DIA-INTERACT",
                        "Interacción Dialéctica Asistida por UniversIA — Oral/Chat",
                    ),
                ],
                help_text="Motor de evaluación. Ref: V06DOC_BLOCKS.",
                max_length=30,
                verbose_name="Tipo de Bloque / Motor",
            ),
        ),
        migrations.AlterField(
            model_name="examitem",
            name="content",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Generado por la IA: stem, options, text_with_gaps, source_text, targets, media_assets, initial_scenario, cloze_options, etc.",
                verbose_name="Contenido del Ítem",
            ),
        ),
        migrations.AlterField(
            model_name="examitem",
            name="estimated_time",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Segundos de resolución esperada. Informativo para la UI.",
                verbose_name="Tiempo Estimado (s)",
            ),
        ),
        migrations.AlterField(
            model_name="examitem",
            name="fail_logic",
            field=models.CharField(
                choices=[
                    ("PENALTY", "Penalización Estándar — Descuento Proporcional"),
                    ("FATAL", "Error Fatal — Nota 0 en la Sección/Destreza Completa"),
                    ("PARTIAL", "Crédito Parcial — Penalización Proporcional al Error"),
                    (
                        "PARTIAL_RETRY",
                        "Reintento Parcial — Solo Destreza Suspensa (CertAcles)",
                    ),
                ],
                default="PENALTY",
                help_text="Determina cómo se gestiona el error en este ítem. Ref: V06DOC_METADATA.",
                max_length=20,
                verbose_name="Lógica de Fallo",
            ),
        ),
        migrations.AlterField(
            model_name="examitem",
            name="grading_logic",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Generado por la IA: correct_answer, gap_solutions (dict {gap_id: answer}), pairs, step_matrix, keywords, feedback_justification.",
                verbose_name="Lógica de Calificación",
            ),
        ),
        migrations.AlterField(
            model_name="examitem",
            name="level_requisite",
            field=models.CharField(
                choices=[
                    ("MANDATORY", "Obligatorio — Todos los niveles"),
                    ("OPTIONAL", "Opcional — Enriquecimiento no evaluable"),
                    ("ADVANCED", "Avanzado — Solo LVL_C o ITIN_MAI/INV"),
                ],
                default="MANDATORY",
                max_length=20,
                verbose_name="Requisito de Nivel",
            ),
        ),
        migrations.AlterField(
            model_name="examitem",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="competency_tag (COMP_*), cognitive_level (COG_*), task_instruction (instrucción de llenado para la IA — preservada tras la generación).",
                verbose_name="Metadatos Pedagógicos",
            ),
        ),
        migrations.AlterField(
            model_name="examitem",
            name="order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
        ),
        migrations.AlterField(
            model_name="examitem",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="assessment_v2.examsection",
                verbose_name="Sección",
            ),
        ),
        migrations.AlterField(
            model_name="examitem",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Peso del ítem en la calificación de la sección (0.1 – 1.0).",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="Peso Relativo",
            ),
        ),
        migrations.AlterField(
            model_name="examitem",
            name="widget_id",
            field=models.CharField(
                choices=[
                    (
                        "W-TECH-CALC",
                        "Consola de Cálculo Procedimental (Ingeniería/Ciencias)",
                    ),
                    (
                        "W-CLIN-SCAN",
                        "Visor de Evidencia Diagnóstica — Zoom HD + Marcadores",
                    ),
                    (
                        "W-OBJ-STRIKE",
                        "Selector de Respuesta con Riesgo (PRM-STRIKE/RBT)",
                    ),
                    (
                        "W-CASE-ECOE",
                        "Estación Clínica ECOE Simulada — Secuencial Non-Backtracking",
                    ),
                    (
                        "W-HUM-TEXT",
                        "Editor de Exégesis Crítica — Pantalla Dividida + Citas",
                    ),
                    (
                        "W-PROC-ACTION",
                        "Panel de Acción Crítica — Checklist de Seguridad",
                    ),
                    (
                        "W-COMM-DIALOG",
                        "Chat Interactivo con UniversIA — Mediación Dialéctica",
                    ),
                    (
                        "W-LAW-NAV",
                        "Navegador de Marco Normativo y Repositorios de Autoridad",
                    ),
                    (
                        "W-PORTFOLIO",
                        "Portafolio Digital de Proceso Creativo (Bellas Artes)",
                    ),
                    (
                        "W-TXT-CLOZE",
                        "Integrador de Huecos en Texto — Open/Multi-Choice Cloze",
                    ),
                    (
                        "W-MIX-MATCH",
                        "Matriz de Vinculación — Drag & Drop Emparejamiento",
                    ),
                    (
                        "W-AUDIO-INSTR",
                        "Reproductor de Audio — Contador de Reproducciones Hermético",
                    ),
                    (
                        "W-PHILO-IPA",
                        "Pad de Transcripción Fonética y Diacrónica (Philo UGR)",
                    ),
                    (
                        "W-PHILO-ECDO",
                        "Editor de Crítica Textual y Colación (Ecdótica UGR)",
                    ),
                    (
                        "W-PHILO-OCR-PALE",
                        "Visor Paleográfico HD con Capa de Transcripción",
                    ),
                    (
                        "W-CALLI-PAD",
                        "Pad Caligráfico — Lenguas No Latinas (Ductus/OCR)",
                    ),
                    (
                        "W-DOC-RESOURCES",
                        "Panel de Recursos Documentales UGR (TRA-TECH)",
                    ),
                    (
                        "W-MUS-SCORE",
                        "Visor de Partitura + Análisis Armónico Anotable (HUM-MUS)",
                    ),
                    (
                        "W-ART-IDENT",
                        "Visor Iconográfico HD — Identificación + Comentario Panofsky",
                    ),
                    (
                        "W-MEDI-LAYOUT",
                        "Interfaz Doble Panel para Transferencia (TRA-TECH/LIT)",
                    ),
                    ("W-OCR-PRO", "Módulo de Auditoría de Producción Manuscrita (OCR)"),
                    (
                        "W-INSTR-SELECTOR",
                        "Selector Multimodal CertAcles (Teclado/Trazos/OCR)",
                    ),
                ],
                help_text="Componente UI. Ref: V06DOC_WIDGETS.",
                max_length=30,
                verbose_name="Widget de Interfaz",
            ),
        ),
        migrations.AlterField(
            model_name="examsection",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="assessment_v2.exam",
                verbose_name="Examen",
            ),
        ),
        migrations.AlterField(
            model_name="examsection",
            name="instructions",
            field=models.TextField(verbose_name="Instrucciones para el Alumno"),
        ),
        migrations.AlterField(
            model_name="examsection",
            name="layout_mode",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Ancho Completo — Sin panel lateral"),
                    ("SPLIT_TEXT", "Panel Lateral de Texto (Reading/Caso/Corpus)"),
                    ("SPLIT_VISUAL", "Panel Lateral Visual (Imagen/Partitura/Obra)"),
                ],
                default="STANDARD",
                help_text="STANDARD: ancho completo. SPLIT_TEXT: panel lateral de texto (Reading/Caso). SPLIT_VISUAL: panel lateral visual (Imagen/Arte/Partitura).",
                max_length=20,
                verbose_name="Modo de Layout",
            ),
        ),
        migrations.AlterField(
            model_name="examsection",
            name="order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
        ),
        migrations.AlterField(
            model_name="examsection",
            name="section_stimulus",
            field=models.TextField(
                blank=True,
                help_text="Texto, HTML o URL de imagen que sirve de contexto compartido para toda la sección. Se renderiza en el Panel Lateral Persistente (SPLIT_TEXT/SPLIT_VISUAL). Ejemplos: texto de lectura (Reading), caso clínico, fuente histórica, partitura URL.",
                null=True,
                verbose_name="Estímulo de Sección",
            ),
        ),
        migrations.AlterField(
            model_name="examsection",
            name="subdivision_id",
            field=models.CharField(
                choices=[
                    ("SD_READ", "Comprensión Lectora (Reading — CLM-UGR)"),
                    ("SD_LIST", "Comprensión Auditiva (Listening — CLM-UGR)"),
                    ("SD_WRIT", "Expresión e Interacción Escritas (Writing — CLM-UGR)"),
                    ("SD_SPEAK", "Expresión e Interacción Orales (Speaking — CLM-UGR)"),
                    ("SD_PHON_GRAPH", "Grafía y Fonética (Minor/Lenguas No Latinas)"),
                    ("SD_MORPH_BASE", "Morfosintaxis y Estructura Elemental (Minor)"),
                    ("SD_LEX_COMM", "Léxico y Función Comunicativa (Minor)"),
                    ("SD_READ_ADAP", "Comprensión Lectora Adaptada (Minor)"),
                    (
                        "SD_CULT_INTEGRITY",
                        "Competencia Intercultural y Contexto (Minor)",
                    ),
                    ("SD_PHONO", "Fonética y Fonología Histórica (Philo UGR)"),
                    ("SD_MORPH_DIAC", "Morfología Diacrónica (Philo UGR)"),
                    ("SD_LEX_SEM", "Lexicología y Semántica Histórica (Philo UGR)"),
                    ("SD_ORTOTYPO", "Corrección Ortotipográfica (Ecdo UGR)"),
                    ("SD_STYLE", "Corrección de Estilo Editorial (Ecdo UGR)"),
                    ("SD_ANNOT", "Anotación Crítica y Edición Científica (Ecdo UGR)"),
                    ("SD_EVAL", "Evaluación Editorial e Informe de Lector (Ecdo UGR)"),
                    (
                        "SD_CORPUS_ANALYSIS",
                        "Investigación y Validación Empírica (Norm UGR)",
                    ),
                    (
                        "SD_MORPH_ANTINORM",
                        "Diagnóstico de Desviaciones Morfosintácticas",
                    ),
                    ("SD_ORTHO_PRESCRIPTIVE", "Ortografía y Ortotipografía Académica"),
                    (
                        "SD_CRITICAL_NORM",
                        "Comentario Crítico y Justificación Bibliográfica",
                    ),
                    ("SD_TRA_ANALYSIS", "Análisis del Encargo Traductológico"),
                    ("SD_TERM_RESEARCH", "Documentación Terminológica y Glosario"),
                    ("SD_TRA_DRAFT", "Traducción Directa Cronometrada"),
                    ("SD_TRA_STYLE", "Análisis Estilístico Comparado (TRA-LIT)"),
                    ("SD_TRA_CREATIVE", "Transferencia Estética (TRA-LIT)"),
                    (
                        "SD_TRA_CRIT",
                        "Comentario Exegético y Justificación Traductológica",
                    ),
                    ("SD_HIST_DEV", "Desarrollo Historiográfico — Prueba Escrita"),
                    ("SD_HIST_PRAC", "Análisis de Fuentes y Comentario Documental"),
                    ("SD_PHIL_TEST", "Test de Precisión Conceptual (Filosofía UGR)"),
                    ("SD_PHIL_DEV", "Preguntas de Desarrollo (Filosofía UGR)"),
                    ("SD_PHIL_TEXT", "Comentario de Texto Filosófico (UGR)"),
                    ("SD_PHIL_ESSAY", "Ensayo Filosófico Argumentado (UGR)"),
                    ("SD_ART_IDENT", "Reconocimiento Iconográfico de Imágenes"),
                    ("SD_ART_ANAL", "Análisis Formal e Iconológico — Panofsky"),
                    ("SD_CREA_PORT", "Portafolio Digital de Proceso Creativo"),
                    ("SD_CREA_MEM", "Memoria de Proceso y Análisis Crítico"),
                    ("SD_MUS_LIST", "Identificación Auditiva Musical"),
                    ("SD_MUS_SCORE", "Análisis en Partitura (Armónico y Formal)"),
                    ("SD_ANTH_TEXT", "Comentario de Fuente Etnográfica o Texto Antr."),
                    ("SD_ANTH_ESSAY", "Disertación Comparativa Intercultural"),
                    ("SD_ANAMNESIS", "Anamnesis y Entrevista Clínica"),
                    ("SD_SYNDROME_BUILD", "Identificación Sindrómica"),
                    ("SD_DIFF_DIAGNOSIS", "Diagnóstico Diferencial"),
                    ("SD_CLINICAL_PRIORITY", "Priorización Clínica y Actuación"),
                    ("SD_ECOE_STATION", "Estación ECOE Cronometrada"),
                    ("SD_ANAT_MACRO", "Anatomía Macroscópica — Nomenclatura TAI"),
                    ("SD_ANAT_RADIO", "Anatomía Radiológica — Semiología RX/RM/TC"),
                    (
                        "SD_HISTO_MICRO",
                        "Histología Microscópica — Identificación Tisular",
                    ),
                    (
                        "SD_HISTO_FORMULA",
                        "Fórmula Leucocitaria — Identificación Morfológica",
                    ),
                    ("SD_FISIO_HOMEO", "Homeostasis y SNA — Fisiología General"),
                    ("SD_FISIO_CARDIO", "Fisiología Cardiovascular (UGR)"),
                    ("SD_FISIO_ECG", "Electrocardiografía — Trazado Normal"),
                    ("SD_FISIO_RESP", "Fisiología Respiratoria y Espirometría"),
                    ("SD_FISIO_RENAL", "Fisiología Renal y Equilibrio Ácido-Base"),
                    ("SD_CUID_NANDA", "Diagnóstico NANDA/NIC/NOC y Plan de Cuidados"),
                    ("SD_CUID_SAFETY", "Protocolo de Seguridad en Técnicas Enfermeras"),
                    ("SD_ODON_RADIO", "Radiología Dental — Ortopantomografía"),
                    ("SD_ODON_PROC", "Procedimiento Técnico Odontológico"),
                    ("SD_FISIO_VAL", "Valoración Funcional — Fisioterapia"),
                    ("SD_FISIO_PALP", "Anatomía Palpatoria — Puntos Gatillo"),
                    ("SD_BIOQUIM_METAB", "Bioquímica Metabólica — Rutas Metabólicas"),
                    ("SD_BIOQUIM_LAB", "Prácticas de Laboratorio Bromatológico (EP)"),
                    (
                        "SD_FARM_FUNDA",
                        "Fundamentos de Farmacología — Mecanismo de Acción",
                    ),
                    (
                        "SD_FARM_CLINICA",
                        "Farmacología Clínica — Selección y Dosificación",
                    ),
                    (
                        "SD_PSY_DIAG",
                        "Diagnóstico DSM-5/CIE-11 — Psicopatología del Adulto",
                    ),
                    (
                        "SD_PSY_EVAL_TECH",
                        "Evaluación Psicológica: Técnicas y Aplicaciones",
                    ),
                    (
                        "SD_PSY_MET_DESIGN",
                        "Métodos y Diseños de Investigación (Psicología)",
                    ),
                    (
                        "SD_PSY_STAT_DATA",
                        "Descripción y Exploración de Datos Psicológicos",
                    ),
                    ("SD_VET_CLIN", "Clínica Animal — Diagnóstico Veterinario (UCO)"),
                    ("SD_VET_CIR", "Cirugía Veterinaria — Procedimientos (UCO)"),
                    ("SD_NUT_DISENO", "Diseño y Evaluación de Dietas — Dietética UGR"),
                    ("SD_NUT_VALORACION", "Valoración del Estado Nutricional (UGR)"),
                    (
                        "SD_BROM_COMPOSICION",
                        "Composición y Valor Nutricional de Alimentos",
                    ),
                    (
                        "SD_BROM_ALTERACIONES",
                        "Alteraciones, Adulteraciones y Calidad Alimentaria",
                    ),
                    (
                        "SD_SPUB_EPIDEMIOLOGIA",
                        "Epidemiología Nutricional y Vigilancia Alimentaria",
                    ),
                    (
                        "SD_SPUB_EDUCACION",
                        "Programas de Educación Nutricional y Comedores",
                    ),
                    (
                        "SD_SPUB_COLECTIVIDADES",
                        "Gestión Alimentación en Colectividades",
                    ),
                    (
                        "SD_PROC_CIV_PRINCIPIOS",
                        "Principios y Presupuestos Procesales Civiles",
                    ),
                    (
                        "SD_PROC_CIV_DEMANDA",
                        "Demanda, Contestación y Proceso Declarativo",
                    ),
                    ("SD_PROC_CIV_EXEC", "Ejecución Forzosa Civil"),
                    ("SD_PROC_CIV_CAUTELAR", "Medidas Cautelares Civiles"),
                    ("SD_PROC_PEN_INVEST", "Instrucción e Investigación Penal"),
                    ("SD_PROC_PEN_CAU", "Medidas Cautelares Penales"),
                    ("SD_PROC_PEN_INTER", "Fase Intermedia y Sobreseimiento Penal"),
                    ("SD_PROC_PEN_JUICIO", "Juicio Oral Penal — Principios y Prueba"),
                    ("SD_PROC_PEN_SENT", "Sentencia Penal y Cosa Juzgada"),
                    ("SD_PROC_PEN_TIPOS", "Tipología de Procesos Penales"),
                    ("SD_PROC_PEN_REC", "Recursos Penales y Ejecución de Sentencia"),
                    ("SD_DICT_CIV_PERSONA", "Persona, Familia y Derecho Civil General"),
                    ("SD_DICT_CIV_OBLIG", "Obligaciones y Contratos Civiles"),
                    ("SD_DICT_CIV_REAL", "Derechos Reales y Propiedad"),
                    ("SD_DICT_PEN_TIPOS", "Tipos Penales y Bien Jurídico Protegido"),
                    (
                        "SD_DICT_PEN_CIRC",
                        "Circunstancias Modificativas de la Responsabilidad",
                    ),
                    ("SD_DICT_PEN_CONCURSO", "Concurso de Delitos y Penas"),
                    (
                        "SD_STAT_FUND",
                        "Estadística y Técnicas Cuantitativas — Fundamentos",
                    ),
                    ("SD_ECON_REGRESION", "Econometría: Regresión y MCO"),
                    ("SD_ECON_SERIES", "Econometría: Series Temporales y Predicción"),
                    ("SD_ACC_FUND", "Contabilidad Financiera — Fundamentos"),
                    ("SD_ACC_ANALISIS", "Análisis de Estados Financieros"),
                    ("SD_STR_ANALISIS", "Análisis Estratégico del Entorno"),
                    ("SD_STR_FORMULA", "Formulación e Implantación Estratégica"),
                    (
                        "SD_MICRO_FUND",
                        "Microeconomía — Teoría del Consumidor y Empresa",
                    ),
                    ("SD_MACRO_FUND", "Macroeconomía — Modelos de Equilibrio"),
                    ("SD_EDU_DUA", "Diseño Universal para el Aprendizaje (DUA/LOMLOE)"),
                    (
                        "SD_EDU_SITUACION",
                        "Situación de Aprendizaje y Programación Didáctica",
                    ),
                    ("SD_EDU_MAES_PROC", "Procesos y Contextos Educativos — MAES UGR"),
                    ("SD_EDU_MAES_DID", "Didáctica Específica — MAES UGR"),
                    (
                        "SD_JOUR_REDACCION",
                        "Redacción Periodística y Géneros Informativos",
                    ),
                    ("SD_JOUR_ETICA", "Ética, Deontología y Verificación (Periodismo)"),
                    ("SD_AV_GUION", "Guion Audiovisual — Literario y Técnico"),
                    ("SD_AV_REALIZACION", "Técnica de Realización y Postproducción"),
                    ("SD_GEOG_SIG_ANALISIS", "Análisis SIG y Cartografía Digital"),
                    ("SD_GEOG_TER_ANALISIS", "Análisis Territorial y Demografía"),
                    ("SD_GEOG_FIS_CLIMA", "Climatología y Geomorfología"),
                    (
                        "SD_WORK_INT_PRAC",
                        "Intervención Social — Práctica y Diagnóstico",
                    ),
                    ("SD_WORK_INT_THEO", "Intervención Social — Teoría y Modelos"),
                    ("SD_WORK_POL_PRAC", "Política Social — Análisis Crítico Práctico"),
                    (
                        "SD_WORK_POL_THEO",
                        "Política Social — Estado de Bienestar y Modelos",
                    ),
                    ("SD_WORK_MED_PRAC", "Mediación Social — Supuestos Prácticos"),
                    ("SD_WORK_MED_THEO", "Mediación Social — Teoría y Modelos"),
                    ("SD_SOFT_ALG", "Algoritmia y Complejidad Computacional"),
                    ("SD_SOFT_DEBUG", "Depuración, Optimización y Patrones de Diseño"),
                    (
                        "SD_SOFT_SE",
                        "Ingeniería del Software — Requisitos y Arquitectura",
                    ),
                    (
                        "SD_CIVIL_CALC",
                        "Cálculo de Estructuras — Esfuerzos y Dimensionado",
                    ),
                    ("SD_CIVIL_NORM", "Cumplimiento Normativo Estructural (CTE/EHE)"),
                    ("SD_INDUS_TERM", "Termodinámica y Ciclos de Potencia"),
                    ("SD_INDUS_TMM", "Teoría de Máquinas — Cinemática y Dinámica"),
                    (
                        "SD_CHEM_BAL",
                        "Balances de Materia y Energía en Procesos Químicos",
                    ),
                    ("SD_CHEM_REACT", "Diseño de Reactores y Cinética Química"),
                    (
                        "SD_ARCH_PROJ",
                        "Proyecto Arquitectónico — Composición y Programa",
                    ),
                    (
                        "SD_URB_PLAN",
                        "Planeamiento Urbanístico y Ordenación del Territorio",
                    ),
                    ("SD_CONS_TECH", "Sistemas Constructivos y Detalle Técnico"),
                    ("SD_CONS_MAN", "Gestión de Obra — Planificación y Seguridad"),
                    (
                        "SD_MATH_PROOF",
                        "Demostración Matemática Formal — Análisis y Álgebra",
                    ),
                    (
                        "SD_MATH_PROB",
                        "Resolución de Problemas Matemáticos Estructurales",
                    ),
                    ("SD_BIO_TEORIA", "Fundamentos Biológicos — Teoría y Concepto"),
                    ("SD_BIO_GENETIC", "Genética, Evolución y Ecología — Problemas"),
                    ("SD_CHEM_TEORIA", "Química Pura — Fundamentos Teóricos"),
                    ("SD_CHEM_SINTESIS", "Síntesis y Reactividad Química — Problemas"),
                    ("SD_PHYS_TEORIA", "Física — Principios y Leyes Fundamentales"),
                    ("SD_PHYS_CALC", "Física — Resolución Analítica de Problemas"),
                    ("SD_GEOL_IDENT", "Identificación Mineralógica y Petrológica"),
                    ("SD_GEOL_STRAT", "Estratigrafía y Lectura de Columnas"),
                    (
                        "SD_GEOL_CARTOG",
                        "Cartografía Geológica e Interpretación de Cortes",
                    ),
                    ("SD_ENV_GESTION", "Gestión de Residuos y Evaluación de Impacto"),
                    ("SD_ENV_CONTAM", "Contaminación — Fuentes, Dispersión y Control"),
                    ("SD_DATA_PROB", "Probabilidad y Modelos Estadísticos (UCM GIDIA)"),
                    ("SD_DATA_INF", "Inferencia Estadística y Contrastes de Hipótesis"),
                    ("SD_DATA_REG", "Regresión y Análisis Multivariante"),
                    (
                        "SD_ML_SUPER",
                        "Aprendizaje Supervisado — Clasificación y Regresión",
                    ),
                    (
                        "SD_ML_UNSUPER",
                        "Aprendizaje No Supervisado y Evaluación de Modelos",
                    ),
                    ("SD_ML_DEEP", "Aprendizaje Profundo y Fundamentos de IA"),
                    ("SD_BIG_ADQUI", "Adquisición, Limpieza y Almacenamiento de Datos"),
                    (
                        "SD_BIG_PROC",
                        "Procesamiento Distribuido — Hadoop/Spark/Streaming",
                    ),
                    ("SD_BIG_ARCH", "Arquitectura de Sistemas de Datos — Lambda/Kappa"),
                    ("SD_THEO", "Validación Teórica — Axiomas y Principios"),
                    ("SD_MODEL", "Modelado Formal — Abstracción Matemática/Lógica"),
                    ("SD_CALC", "Precisión Algorítmica — Cálculo Procedimental"),
                    ("SD_VERIF", "Verificación Normativa — Coherencia y Cumplimiento"),
                    ("SD_FACT", "Extracción y Jerarquización de Hechos Relevantes"),
                    ("SD_NORM", "Encuadre en Ordenamiento Legal o Protocolo Clínico"),
                    (
                        "SD_PROC",
                        "Ejecución Procedimental — Tramitación o Maniobra Clínica",
                    ),
                    (
                        "SD_ETHI",
                        "Evaluación Deontológica — Bioética o Seguridad Jurídica",
                    ),
                    ("SD_SOURCE", "Crítica de Fuentes Primarias — Análisis Documental"),
                    ("SD_DISC", "Construcción Discursiva — Ensayo Crítico Argumentado"),
                    (
                        "SD_ARTE",
                        "Validación Artística — Técnica Matérica y Composición",
                    ),
                ],
                help_text="Identificador técnico de la subdivisión. Ref: V06DOC_SUBDIVISIONS.",
                max_length=60,
                verbose_name="ID Subdivisión",
            ),
        ),
        migrations.AlterField(
            model_name="examsection",
            name="time_limit",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Segundos. 0 = sin límite. Non-Backtracking activo si > 0.",
                verbose_name="Límite de Tiempo (s)",
            ),
        ),
        migrations.AlterField(
            model_name="examsection",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Título de la Sección"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="exam",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submission",
                to="assessment_v2.exam",
                verbose_name="Examen",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="final_score",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Valor en rango 0.0000 – 1.0000. Multiplicar por 10 para escala UGR.",
                max_digits=5,
                null=True,
                verbose_name="Nota Final",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="graded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Calificado a las"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="grading_report",
            field=models.JSONField(
                help_text='Contrato: {"sections": [{"subdivision_id", "title", "items": [{"item_id", "item_score", "feedback_category", "justification", ...}], "section_score", "status"}], "global_flags": [...], "feedback_stats": {...}, "qualitative_summary": "..."}',
                null=True,
                verbose_name="Informe de Calificación",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="passed",
            field=models.BooleanField(default=False, verbose_name="Superado"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="section_scores",
            field=models.JSONField(
                blank=True,
                help_text='{ "<subdivision_id>": <score_0_to_1> }. Usado para gating no-compensación.',
                null=True,
                verbose_name="Calificaciones por Sección",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="student_responses",
            field=models.JSONField(
                help_text='Contrato: {"responses": {"<item_id>": <raw_input>}}. raw_input varía por widget.',
                null=True,
                verbose_name="Respuestas del Estudiante",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submitted_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Entregado a las"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["user", "status"], name="assessment__user_id_6228a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["status", "created_at"], name="assessment__status_1c1177_idx"
            ),
        ),
    ]
