# Generated by Django 5.0.7 on 2026-08-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_v2", "0020_hito6_v59_full_taxonomy"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="difficulty_mode",
            field=models.CharField(
                choices=[
                    ("UGR", "Estándar UGR (por defecto)"),
                    ("ENDURECIDO", "Endurecido (penalización + distractores extra)"),
                ],
                default="UGR",
                max_length=20,
                verbose_name="Modo de Dificultad",
            ),
        ),
    ]
