# Generated by Django 5.0.7 on 2026-08-06 00:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_v2", "0021_exam_difficulty_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenusage",
            name="estimated_cost_usd",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("0.0"),
                max_digits=10,
                verbose_name="Coste Estimado (USD)",
            ),
        ),
    ]
