# Generated by Django 5.0.7 on 2026-08-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_v2", "0022_alter_tokenusage_estimated_cost_usd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="difficulty_mode",
            field=models.CharField(
                choices=[
                    ("UGR", "Acreditación Estándar (por defecto)"),
                    ("ENDURECIDO", "Endurecido (penalización + distractores extra)"),
                ],
                default="UGR",
                max_length=20,
                verbose_name="Modo de Dificultad",
            ),
        ),
    ]
