# Generated by Django 5.0.7 on 2025-10-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaintenanceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_mode_active",
                    models.BooleanField(
                        default=False,
                        help_text="Marcar para activar la página de mantenimiento para los usuarios. Los superusuarios y IPs permitidas seguirán teniendo acceso.",
                        verbose_name="Activar Modo Mantenimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Mantenimiento",
                "verbose_name_plural": "Configuración de Mantenimiento",
            },
        ),
    ]
